### ISSUE TITLE
Looking for volunteers to nominate/submit brew formula to Homebrew core

### ISSUE THREAD

**Issue by ahmetb** [ahmetb/kubectx#10]
It is frowned upon for a package owner to submit a formula to Homebrew core formulae repository.

Once this repository reaches [50 stars](https://github.com/Homebrew/brew/blob/master/docs/Acceptable-Formulae.md) (which it recently did), I encourage someone from kubectx user community to submit our [existing formula`](https://github.com/ahmetb/kubectx/blob/master/Formula/kubectx.rb) to [homebrew-core](https://github.com/Homebrew/homebrew-core).

This formula passes the `brew audit --new-formula  Formula/kubectx.rb` check.

**Comment by koenrh** [comment]
I have read the Homebrew docs, ran the audit/check scripts, and submitted a PR: https://github.com/Homebrew/homebrew-core/pull/14207.

**Comment by ahmetb** [comment]
This is now done! Thanks @koenrh 

Folks can reinstall it from Homebrew-core with:

    brew untap ahmetb/kubectx && brew uninstall --force kubectx && brew update && brew install kubectx
