### ISSUE TITLE
Rename with same alias to a different k8s cluster actually deletes the prior aliased cluster credentials in kube config

### ISSUE THREAD

**Issue by ye** [ahmetb/kubectx#104]
I made a mistake in rename/aliasing the k8s cluster with the wrong target(cluster1). So I redo the rename with the same alias name(qa2) but point to a different target (cluster2). After that, cluster1 was removed in my k8s kube config file.

See below:
```bash
$ kctx
gke_foobar-corp-image-builder_us-central1-a_gitlab-k8s
gke_foobar-corp-qa2_us-central1-a_foobar
gke_foobar-corp-qa_us-central1-a_foobar
gke_foobar-corp-qa_us-central1-b_qa2
gke_foobar-corp-ye-dev_us-central1-a_gitlab-k8s
gke_foobar-corp-ye-dev_us-central1-a_foobar
gke_foobar-corp_us-central1-a_foobar-production
minikube
$ kctx qa2=gke_foobar-corp-qa2_us-central1-a_foobar
Context "gke_foobar-corp-qa2_us-central1-a_foobar" renamed to "qa2".
$ kctx qa2=gke_foobar-corp-qa_us-central1-b_qa2
$ kctx
gitlab
gke_foobar-corp-ye-dev_us-central1-a_gitlab-k8s
gke_foobar-corp_us-central1-a_foobar-production
minikube
qa
qa2
ye
$ rg gke_foobar-corp-qa2_us-central1-a_foobar ~/.kube/config | wc -l
       0
```
I think this is a dangerous side effect of renaming and it shouldn't implicitly delete kube cluster credentials in the kube config.

**Comment by ahmetb** [comment]
I think you're basically doing

```
$ kubectx
1
2

$ kubectx a=1

$ kubectx a=2

# at this point 1 is deleted
```

this is expected. (I'll close this as wontfix if I don't get an answer in a couple of weeks).

Please take a look at the code, we're not doing anything but "kubectl config delete-context" (if specified name already exists) and "kubectl config rename-context":

https://github.com/ahmetb/kubectx/blob/b584d14f90eac8936468fb0751a87494a67d5f72/kubectx#L143-L157

So if your credentials in kubeconfig are deleted, I suspect kubectl is to blame here.

Are you seeing the `user` and `cluster` entries (in kubeconfig file) deleted for the cluster 1 in this case –or just the `context` entry?
