### ISSUE TITLE
Proposal: Only show current context

### ISSUE THREAD

**Issue by nickradford** [ahmetb/kubectx#121]
It would be nice (when writing tools around kubectx) to only show the current context, maybe something like

```sh
$ kubectx --current
```

Which would only output your current context, not all contexts and highlighting the current one.

**Comment by nickradford** [comment]
Realizing now that there's `kubectl config current-context`, but wouldn't be a terrible feature to add here.

**Comment by ahmetb** [comment]
This came up too many times. kubectx with no args already shows the current context 

Consider using: kubectl config current-context. (make an alias to it).

**Comment by ahmetb** [comment]
Just saw your 2nd comment.

It came up many times, and we want the kubectx tool to be interactive, and not something you script around. When you run "kubectx", as long as you have colors in your terminal, you'll see the active context.

Maybe we'll revisit the idea of `-c` someday. This came up far too many times, but when I pushed back on it, it was not a showstopper for anyone. This makes me think we can strive for fewer flags/options.

**Comment by nickradford** [comment]
Totally, just didn't realize it was already supported by `kubectl`.  Definitely not a showstopper. Thanks for the quick and helpful response!

**Comment by adubkov** [comment]
I think kubectx should support is as well. It is just more natural to get current context when you managing contexts via kubectx.

**Comment by ahmetb** [comment]
You’re not supposed to use kubectx for scripting. 

All of the functionality provided by kubectx is already in kubectl (read the source code). Kubectx is a tool strictly for interactive use.

**Comment by nickradford** [comment]
I mean, it's one thing to tell people you're not supposed to use something for scripting, but people still will. I used `kubectx` to write a script to rename contexts for the application I'm working on.

I tend to agree with @adubkov because if you're using kubctx regularly to switch contexts, it's natural to want to only see the current context if you have that need for some reason (like scripting). 

Also, you've said this has come up a lot. Your users want this functionality, and it's pretty trivial to add, so it may not be a bad thing to implement.

**Comment by ahmetb** [comment]
@nickradford  I'm finally coming around to implement a feature to show current context/namespace. Please vote for it at https://github.com/ahmetb/kubectx/issues/127, I also would like to hear your opinions.

**Comment by joelmellon** [comment]
> kubectx with no args already shows the current context

No, it **_highlights_** the current context. It's incredibly difficult to detect which line is highlighted programatically. Give it a shot.

**Comment by joelmellon** [comment]
@ahmetb 

> kubectx with no args already shows the current context

No, it **_highlights_** the current context. It's incredibly difficult to detect which line is highlighted programatically. Give it a shot.

**Comment by ahmetb** [comment]
@joelmellon kubectx is not meant for programatical invocation. Use kubectl for that please. Also we have "kubectx -c" now.
