### ISSUE TITLE
kctx and kns isn't working with short names on Macos

### ISSUE THREAD

**Issue by rbizzell40** [ahmetb/kubectx#122]
brew install kubectx --with-short-names
Updating Homebrew...
Warning: kubectx: this formula has no --with-short-names option so it will be ignored!
 When I issue kctx or kns in the zsh shell command not found

**Comment by ahmetb** [comment]
See #112. Homebrew no longer supports options.

**Comment by rbizzell40** [comment]
So what is the fix for this now

**Comment by ahmetb** [comment]
As you see the issue is still open. Subscribe to stay in the loop.

**Comment by rbizzell40** [comment]
Ok thanks will do
