### ISSUE TITLE
Proposal: Add --version flag for kubectx and kubens

### ISSUE THREAD

**Issue by cbeneke** [ahmetb/kubectx#125]
When having multiple versions of kubectx installed it is currently not possible to differentiate between the versions except with looking into the code and comparing the recent changes (or checking the git tags).
As commented in https://github.com/ahmetb/kubectx/pull/124 hardcoding the values is error-prone. This issue is for discussion how to implement this in a good way :)

**Comment by cbeneke** [comment]
I thought about some automated variants of this, imho a git hook would be the most elegant version, as you can not forget updating the version. In my head a pre-commit and a serverside post-receive are reasonable.

1) pre-commit hook: This can be calculated on client-side and automatically update a variable in the scripts. git does not know about the future hash though, so that you would run into an off-by-one error (imho you can only use the last existing commit hash). Also tags do not trigger a pre-commit hook.
2) post-receive hook/webhook: This is more powerful, but needs to be hosted somewhere and needs push access to the repo then to update the hashes

Please feel free to enlighten me, if there is another (better) solution which is not hardcoded :)

**Comment by ahmetb** [comment]
I recommend we hold off on this until we do #115 (Go rewrite). Once we start distributing in Go, we will be able to publish binaries from the release environment, which will give us ability to "stamp" the binaries on "tag commits" where we can just read the version from `git describe --tags --always` easily.

**Comment by tyrken** [comment]
Bump for this now we have the go rewrite - and I think you are using goreleaser which has native functionality to write the current git-sha into a golang global at link-time, which would be enough for now if reported via the `--version` command.

Human readable version numbers in the `--version` response would be nice also.

**Comment by coolaj86** [comment]
Following.

This is also an issue for the **Webi** installer https://webinstall.dev/kubectx https://github.com/webinstall/webi-installers/pull/175

**Comment by coolaj86** [comment]
Since you're using goreleaser, this would be a good fix:

```go
var (
	name    = "gitdeploy"
	version = "0.0.0"
	date    = "0001-01-01T00:00:00Z"
	commit  = "0000000"
)

func ver() string {
	return fmt.Sprintf("%s v%s (%s) %s", name, version, commit[:7], date)
}

func main() {
	// Support [--]version and -V
	if len(os.Args) > 1 {
		if "version" == strings.TrimLeft(os.Args[1], "-") || "-V" == os.Args[1] {
			fmt.Println(ver())
			os.Exit(0)
			return
		}
	}

	// ...
}
```

**Comment by z0mbix** [comment]
Hi, could this be implemented now that the go rewrite is being built and released?

**Comment by ahmetb** [comment]
Thanks all, I made patch #295, it'll be available in the next release.
