### ISSUE TITLE
Proposal: add option to print current {context, namespace}

### ISSUE THREAD

**Issue by ahmetb** [ahmetb/kubectx#127]
A lot of people want to see the name of the current context/namespace in `kubectx`/`kubens`. This came up in forms of feature requests and pull requests SO MANY TIMES:

> - #14: Add `-c`, `--current` option to get **current context** 
> - #28: Get **current context** with `-c`
> - #43: adds an option to print the **current context/namespace** (`-c`/`--current`)
> - #51: add `-c`/`--current` to show **current context**
> - #62: add `?` command to get the **current namespace**
> - #61: add `kubens current` command to display **current namespace**
> - #100: Add feature and flag to print **current context / namespace**  (`--current`)
> - #121: Proposal: Only show current context (`--current`)
> - #132: add a option to query current NS (`-q`)
> - #142: add a switch `--current` for printing current namespace
> - #168: Option for printing only the current context/namespace `-c`

Thank you all for bringing this up so many times, clearly I need to change my mind about this, so here are some arguments for/against making this change:

## Arguments "against"

1. We already highlight current context/namespace when you run these kubectx/kubens with no arguments

1. You can find the current context/namespace through native kubectl commands

    - `kubectl config current-context` (reasonable)
    - `kubectl config view -o=jsonpath="{.contexts[?(@.name==\"$(kubectl config current-context)\")].context.namespace}"` (not really)

1. Adding yet another flag will increase the interaction surface. Where do we stop adding new flags? Isn't this already possible via kubectl?

## Arguments "for"

- I don't want to call a long kubectl command or have a long alias, I just want it all in one place. (👍)

- If I have a lot of clusters or namespaces, running `kubectx` or `kubens` prints output that exceed my terminal height, so I cannot see highlighted item (in yellow font) without scrolling. (👍)

- My script uses kubectx, so I need the current context. (⚠️ kubectx/kubens are not supported for calling from headless scripts, they are designed to be interactive commands). (👎)

## Designs considered (please add more in comments)

1. **Option 1:** Add `-c` flag. It's also in line with the current flags we have (`-d`, `-h`...)
    - This seems intuitive as it's proposed independently by multiple people. (see above)
    - Do we do just `-c`, or also `--current` (I personally prefer just `-c`.)

1. **Option 2:** Add `?` subcommand. It looks nice, and short: `kubectx ?` and looks similar to `kubectx -`, but it is unconventional. It's
    - This is the first option that came to my mind, and also proposed in #62.
    - printing current context is more of a “command” than an “option” , so this fits better. 

----

Your comments are appreciated, so I'm adding a couple of polls for you to vote:

**Should we make this change?**
[![](https://api.gh-polls.com/poll/01D2H5A22FSMG074R7K85YM7JG/Implement%20this)](https://api.gh-polls.com/poll/01D2H5A22FSMG074R7K85YM7JG/Implement%20this/vote)
[![](https://api.gh-polls.com/poll/01D2H5A22FSMG074R7K85YM7JG/Do%20not%20implement)](https://api.gh-polls.com/poll/01D2H5A22FSMG074R7K85YM7JG/Do%20not%20implement/vote)

**If so, which design should we go for?**
[![](https://api.gh-polls.com/poll/01D2H5A3M1E2TP02DTDD333TS6/Add%20flags%20both%20-c%20and%20--current)](https://api.gh-polls.com/poll/01D2H5A3M1E2TP02DTDD333TS6/Add%20flags%20both%20-c%20and%20--current/vote)
[![](https://api.gh-polls.com/poll/01D2H5A3M1E2TP02DTDD333TS6/Add%20flag%20-c)](https://api.gh-polls.com/poll/01D2H5A3M1E2TP02DTDD333TS6/Add%20flag%20-c/vote)
[![](https://api.gh-polls.com/poll/01D2H5A3M1E2TP02DTDD333TS6/Make%20it%20a%20command%3A%20'kubectx%20%3F')](https://api.gh-polls.com/poll/01D2H5A3M1E2TP02DTDD333TS6/Make%20it%20a%20command%3A%20'kubectx%20%3F'/vote)

**Comment by rcoup** [comment]
@ahmetb is 80x enough votes?

**Comment by glensc** [comment]
I have 4th argument (it's a combination of 1 and 3): I use `kubectx` to change the namespace, so it is intuitive it can just print current namespace. I need for scripting:
1. save namespace
2. switch namespacex
3. switch namespacey
4. restore namespace

While I have the solution now, I searched and found from this ticket I can use `kubectl config current-context`. but I still had to spend time to do research, which could be avoided if `kubectx` is able to print the current ns/ctx itself.

**Comment by OJFord** [comment]
> (⚠️ kubectx/kubens are not supported for calling from headless scripts, they are designed to be interactive commands). (👎)

Though they both already check for interactivity (that stdout is a tty) so that `kubens | cat` for example displays the full list even with `fzf` installed.

> Add ? subcommand. It looks nice, and short: kubectx ? and looks similar to kubectx -, but it is unconventional. [...] printing current context is more of a “command” than an “option” , so this fits better.

I'd suggest that 'only active' is an option to the command 'list', and the command for that is `kubectx`/`kubens`.

**Comment by JulienBreux** [comment]
Hello @ahmetb  👋 

🆙

**Comment by ahmetb** [comment]
Sorry for the latency here folks. Earlier in the pool, the options were very close to each other. It seems like `-c/--current` has pulled away. I still think `?` is the cleanest, but we should proceed with `-c`/`--current`.

I'll prepare a patch and release soon.

**Comment by ahmetb** [comment]
This is now fixed and released as v0.7.0. Thanks for participating in the decision-making process by voting in this issue.

**Comment by JulienBreux** [comment]
@ahmetb Thanks a lot 😊 
Sorry @OJFord, but I'm repos owner too and sometime a ping is not bad ;)

Have a good day guys!
