### ISSUE TITLE
Intermittently get "Failed to read /dev/tty error: you did not choose any of the options" in Interactive mode

### ISSUE THREAD

**Issue by indrayam** [ahmetb/kubectx#131]
OS: Ubuntu 16.04
fzf version: 0.17.5 (b46227d)
Not sure how to get the version I am using of kubectx and kubens

When I run kubens or kubectx, I get this error:
```
Failed to read /dev/tty
error: you did not choose any of the options
```

I do not get this on my MacOS. Not sure if there is something wrong in my configuration. 

Update: Seems like this issue might be the culprit: https://github.com/junegunn/fzf/issues/1486

**Comment by ahmetb** [comment]
Yeah we got this issue several times now. fzf or a kernel issue seems to be the culprit.

**Comment by ahmetb** [comment]
Closing as the same issue as #128.
