### ISSUE TITLE
kubens: failing to get the namespace list

### ISSUE THREAD

**Issue by vin4git** [ahmetb/kubectx#133]
I have 3 clusters added in "KUBECONFIG". I'm able to switch to clusters using "kubectx" but unable to list the namespaces except for the first cluster which is there in "KUBECONFIG". Below are details:

$ echo $KUBECONFIG
/Users/XXX/kubeconfig_admin_cluster1:/Users/XXX/kubeconfig_admin_cluster2:/Users/XXX/kubeconfig_admin_cluster3

$ kubectx admin@cluster2
Switched to context "admin@cluster2".

**$ kubens
error: the server doesn't have a resource type "namespaces"
error getting namespace list**

$ kubectx admin@cluster1
Switched to context "admin@cluster1"

$ kubens
env1
env2
env3
..
...
....

Unable to list the namespaces for 2nd and 3rd clusters. Kindly help in this regards.

**Comment by ahmetb** [comment]
Something's wrong with your cluster of kubeconfig.

Run `kubectl get namespaces` and you'll see the same error.

**Comment by vin4git** [comment]
Yes, I'm getting the same error when I run "kubectl get namespaces" for cluster2 & cluster3.

But when I explicitly add the KUBECONFIG for cluster2 & cluster3 individually then "kubectl get namespaces" is working. 

**$ export KUBECONFIG=/Users/XXX/kubeconfig_admin_cluster2

$ kubectx
admin@cluster2

$kubens
env4
env5
env6
..
...
....**

If the issue is with the cluster of kubeconfig then we would have got the same namespace errors. But we dint get these errors so I suspect the issue is with kubens.

**Comment by ahmetb** [comment]
@vin4git please read the source code for kubens, it's only 200 lines of bash.

You can run kubens with environment variable `DEBUG=1` set and what you will see is that it's nothing but a tool that calls `kubectl get namespaces`.

If it's failing, I am suspicious it's something wrong with your cluster. That + the vast user base of kubectx/kubens makes me think it's a problem with your setup.
