### ISSUE TITLE
Weird output running kubectx

### ISSUE THREAD

**Issue by williamokano** [ahmetb/kubectx#146]
Every command I execute on `kubectx` I got similar output to the following, which was just a `kubectx --help`

```bash
+ set -eou pipefail
+ IFS='
	'
+ SELF_CMD=/usr/local/bin/kubectx
+ KUBECTX=/Users/william/.kube/kubectx
+ main --help
+ hash kubectl
+ KUBECTL=kubectl
+ [[ 1 -eq 0 ]]
+ [[ --help == \-\d ]]
+ [[ 1 -gt 1 ]]
+ [[ 1 -eq 1 ]]
+ [[ --help == \- ]]
+ [[ --help == \-\h ]]
+ [[ --help == \-\-\h\e\l\p ]]
+ usage
+ cat
USAGE:
  kubectx                       : list the contexts
  kubectx <NAME>                : switch to context <NAME>
  kubectx -                     : switch to the previous context
  kubectx <NEW_NAME>=<NAME>     : rename context <NAME> to <NEW_NAME>
  kubectx <NEW_NAME>=.          : rename current-context to <NEW_NAME>
  kubectx -d <NAME> [<NAME...>] : delete context <NAME> ('.' for current-context)
                                  (this command won't delete the user/cluster entry
                                  that is used by the context)

  kubectx -h,--help         : show this message
```

Any ideas what may be causing it? Installed through `brew install` on macos 10.14.4 and iterm2.

Error occurs on `fish` (3.0.0) and on `bash` (3.2.57(1)). 

`brew info kubectx` output:
```bash
kubectx: stable 0.6.3, HEAD
Tool that can switch between kubectl contexts easily and create aliases
https://github.com/ahmetb/kubectx
/usr/local/Cellar/kubectx/0.6.3 (12 files, 32.7KB) *
  Built from source on 2019-04-23 at 11:05:33
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/kubectx.rb
```

**@edit** checking on other issues, I realized that some other people had the same error as me and looks like it was related to `fzf`. Problem is, I don't have `fzf` installed on my mac.

I tried to run `kubectx` with the env `KUBECTX_IGNORE_FZF=1` and still don't work. Don't know if it was ignored or if it was wrong. On `fish`, I ran as following `env KUBECTX_IGNORE_FZF=1 kubectx --help`, same _weird_  output.

**Comment by ahmetb** [comment]
Looks like your DEBUG environment variable is set? (:

**Comment by williamokano** [comment]
@ahmetb hi, I will check, thanks for the answer.

**Comment by jtara1** [comment]
add `unset DEBUG` to your .bashrc or .bash_profile if you have a chaotic mess of configs like me and reload sh env with `$ bash` and check if it's set or not with `$ env | grep DEBUG`
