### ISSUE TITLE
kubens error with kubectl 1.12

### ISSUE THREAD

**Issue by yads** [ahmetb/kubectx#148]
When I run kubens with kubectl 1.12 I get the error:
```
Error from server (Forbidden): namespaces ".items[*].metadata.name}{@}{\"\\n\"}{end}" is forbidden: User "vkazakov" cannot get namespaces in the namespace ".items[*].metadata.name}{@}{\"\\n\"}{end}"
error getting namespace list
error: could not list namespaces (is the cluster accessible?)
```

However when I run it with kubectl 1.10 it works fine. I've tracked the error down to the command `kubectl get namespaces -o=jsonpath="{range .items[*].metadata.name}{@}{\"\n\"}{end}"`. If I remove the space between `range` and `.items` like so `kubectl get namespaces -o=jsonpath="{range.items[*].metadata.name}{@}{\"\n\"}{end}"` kubens is able to get the list of namespaces.

This is on OSX.

**Comment by ahmetb** [comment]
You mean 1.12, right?

**Comment by yads** [comment]
@ahmetb yes, thanks for that.

**Comment by ahmetb** [comment]
The command `kubectl get namespaces -o=jsonpath="{range .items[*].metadata.name}{@}{\"\n\"}{end}"` works fine for me on kubectl 1.14 (and tens of thousands of users out there).

Docs are here: https://kubernetes.io/docs/reference/kubectl/jsonpath/ I'm hesitant about removing that space, please open an issue about kubectl if you’re consistently seeing the problem.

**Comment by yads** [comment]
Just to confirm, it is working with 1.14 for me. Must have been an issue for 1.12 only.

**Comment by ahmetb** [comment]
Weird.
I tried with 1.12.8 and 1.12.0 binaries as well, there doesn't seem to be a problem for me.

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.12.md
