### ISSUE TITLE
erro: open: *.lock: file exists

### ISSUE THREAD

**Issue by bclark8923** [ahmetb/kubectx#151]
I'm trying to switch context but I keep getting 

`bclark@bclark-dt-01:~/Documents/projects$ kubectx gke-prod-us-west1`
`error: open /home/bclark/.kube/config.d/paas-gke-dev.lock: file exists`

I'm switching from `gke-dev-us-west1` context

No information on this error, the file doesn't exist at all, I tried creating and deleting that file and the same error is thrown every time.

Any ideas where this could stem from?

**Comment by ahmetb** [comment]
Hmm, never seen config.d/.
What’s your kubectl version?

**Comment by ahmetb** [comment]
Kubectl doesn’t support config.d/. 

I don’t know what you’re using but I suspect your kubectl is broken.
