### ISSUE TITLE
Completions don't work

### ISSUE THREAD

**Issue by jwenz723** [ahmetb/kubectx#157]
I have installed kubectx and kubens using the brew installation `brew install kubectx`. The README states:

> This command will set up bash/zsh/fish completion scripts automatically.

The installation succeeded, and I am able to use both kubectx and kubens, however completions are not working (assuming I'm doing it right).  I type `kubectx esc` (where esc is the first 3 letters of my context that is returned by running `kubectx`) then hit `<tab><tab>` and nothing happens.

If I type `kubectx ` then hit `<tab><tab>` my shell just starts running through all the directories in my current path (pwd).

I'm on MacOS Mojave (10.14.5)
My shell is oh-my-zsh with robbyrussell theme

I do see that the completion scripts are installed by brew in a location that is on `fpath`:

```
➜  ~  echo $fpath
/Users/jeff.wenzbauer/.oh-my-zsh/plugins/kube-ps1 /Users/jeff.wenzbauer/.oh-my-zsh/plugins/kubectl /Users/jeff.wenzbauer/.oh-my-zsh/plugins/history /Users/jeff.wenzbauer/.oh-my-zsh/plugins/git /Users/jeff.wenzbauer/.oh-my-zsh/functions /Users/jeff.wenzbauer/.oh-my-zsh/completions /usr/local/share/zsh/site-functions /usr/share/zsh/site-functions /usr/share/zsh/5.3/functions
➜  ~  ls /usr/local/share/zsh/site-functions
_brew               _brew_cask          _brew_services      _git                _helm               _kubectl            _kubectx            _kubens             git-completion.bash linkerd
```

**Comment by ahmetb** [comment]
If you search "completions" in the issue tracker, there are many issues that came up in the. Maybe you're not using `zsh-completions` plugin in oh-my-zsh. Maybe you need to do a `autoload -U compinit && compinit`. Hard to tell...

I'm inclined to close this, as it probably works for hundreds of other users out there, and likely a setup issue with you.

**Comment by trondhindenes** [comment]
`autoload -U compinit && compinit` was what was missing for me.

**Comment by jwenz723** [comment]
Yep, that was the problem. I had to install [zsh-completions](https://github.com/zsh-users/zsh-completions#using-zsh-frameworks) and then add into ~/.zshrc:

```
plugins=(… zsh-completions)
autoload -U compinit && compinit
```

**Comment by zroupas** [comment]
Hi and sorry for commenting to a closed case but I was wondering what am I missing and cannot fix the autocompletion when it comes to kubectx/kubens in mac Monterey. I have
* installed kubectx via homebrew
* have installed zsh-completions and add the appropriate config to my .zshrc
`plugins=(git docker docker-compose zsh-completions)
autoload -U compinit && compinit`
* source ~/.zshrc

but nothing, when I try to kubectx <tab> I only get the documents/folder that are present in the folder that I'm running the binary from. I have also tried to rebuild zcompdump but nothing

* rm -f ~/.zcompdump; compinit

Probably this is something on my end but I cannot figure why kubectx/kubens cannot suggest contexts or namespaces. kubectl works like a charm though so if anyone has any suggestion please let me know

Thanks in advance

**Comment by ahmetb** [comment]
Try not to mess with the completion scripts if you're installing via Homebrew. It should do the right thing out of the box, especially with oh-my-zsh.

**Comment by zroupas** [comment]
Thanks for the advice.I really appreciate taking the time to respond and i totally agree but what do you do if the autocompletion doesn’t work out of the box after installing via homebrew which is the recommended way?

**Comment by onurguzel** [comment]
Sorry for posting into a closed issue. I was having the same issue and I want to share the solution. After investigating homebrew formula, I've noticed that homebrew installs completion scripts into a path which IS NOT in the `FPATH` by default.

Modifying `.zshrc` file should work:
```zsh title=".zshrc"
if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh-completions:$(brew --prefix)/share/zsh/site-functions:$FPATH

  autoload -Uz compinit
  compinit
fi
```

**Comment by vincentvictoria** [comment]
The brew [documentation](https://docs.brew.sh/Shell-Completion) states

```
Homebrew comes with completion definitions for the brew command.
Some packages also provide completion definitions for their own programs.

You must manually configure your shell to enable its completion support. 
```
So, if you didn't configure completion for brew, any packages installed by brew may not work.

If you use ohmyzsh, adding `FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"` before `source $ZSH/oh-my-zsh.sh` in `.zshrc` is sufficient.
