### ISSUE TITLE
Dot files support?

### ISSUE THREAD

**Issue by allcentury** [ahmetb/kubectx#158]
Would you be open to a pull request that supports a dotfile for kubens/kubect where a change in $PWD that has either of those files automatically invokes `kubectx` or `kubens`?

For example:

```
% cat .kubens
my-namespace
% cat .kubectx
my-cluster
```

This is akin to something like version managers for programming languages like [rvm](https://rvm.io/).

**Comment by ahmetb** [comment]
Interesting idea, but that ("automatically invoking when $PWD changes") usually requires integrating into the shell. Does https://direnv.net/ get you somewhere closer?

**Comment by allcentury** [comment]
@ahmetb that's cool, haven't seen that before!  It seems like we'd use ENV vars here instead which would also work.  I have something working for bash/zshrc but yes you are correct, in my bashrc I have:

```
source /usr/local/share/kubectx/auto.sh
```

**Comment by ahmetb** [comment]
Yeah, I'd recommend folks to use direnv for these purposes.
It would be better to keep the scope of this tool narrow and utilize other focused tools for that job.

**Comment by allcentury** [comment]
I'm not sure I follow, I don't believe k8s supports env vars to set context/namespace based on [this PR] (https://github.com/kubernetes/kubernetes/pull/60044).  Do you have suggestion on how to autoswitch w/ direnv?

**Comment by ahmetb** [comment]
`direnv` lets you run commands by listing them in `.envrc`.
It doesn't have to be environment variables.

See these links for examples:
- https://github.com/direnv/direnv/wiki
- https://github.com/cloudpilots/gkubenv
