### ISSUE TITLE
Proposal: add delete key functionality to fzf

### ISSUE THREAD

**Issue by argamanza** [ahmetb/kubectx#165]
I already implemented it and would push and create pull request on demand - 
Simple addition that'll allow the user to press the `delete` key to delete the selected context/namespace.

I'm aware to the fact that there's already an implementation in the form of `kubectx | xargs kubectx -d` but on the other hand you could say the same thing about using `kubectx` instead of the normal `kubectl` commands, it's a little handy short way to delete unwanted contexts using one key.

> Edit: for some reason i forgot the **Proposal** label, sorry for that.

**Comment by ahmetb** [comment]
Not very UNIX-y IMO, and not many people use this tool with fzf, so I'm a bit hesitant to add this. Also a pretty cryptic feature (in terms of discoverability), not to mention if people hit &larr;delete key accidentally without realizing what it does, it's a problem.

Also I assume fzf has a support for capturing delete key? What if user specifies a non-fzf completion tool (which is actually we support I think).

**Comment by ahmetb** [comment]
Also worth mentioning there might be a Go rewrite of this tool soon (#115), in that case we'd ditch fzf probably, so any fzf-specific implementation detail might not be carried over.

**Comment by argamanza** [comment]
You're right, i haven't thought on most of the things you mentioned.
Anyway i guess the `-d` option is enough for most of the cases.
