### ISSUE TITLE
Homebrew: does zsh completions work?

### ISSUE THREAD

**Issue by kivagant-ba** [ahmetb/kubectx#169]
I have installed kubectx with `brew install kubectx` but I can't see any completion suggestions.

How to check if it was installed correctly?

Thank you.

**Comment by kennethtxytqw** [comment]
It doesn't work for me either.

**Comment by ahmetb** [comment]
Works for me just fine on my oh-my-zsh.

Does adding this to your .zshrc solve the problem:

    autoload -U compinit && compinit

**Comment by kennethtxytqw** [comment]
Thanks @ahmetb this worked for me.

**Comment by myannou** [comment]
adding
`autoload -U compinit && compinit`
after source $ZSH/oh-my-zsh.sh

solve this issue also for me.
thanks
