### ISSUE TITLE
[INFORMATION SHARE]   A web based kubectl tool.

### ISSUE THREAD

**Issue by zhangliqiang** [ahmetb/kubectx#179]
Hi there,

We developed a web based kubectl tool, which enables you to manage kubernetes credentials and run kubectl command in web browser.

https://github.com/webkubectl/webkubectl

Hopefully it's useful for you guys.

@ahmetb kubectx is an excellent tool, we are planning to support kubectx in webkubectl. :blush:

**Comment by zhangliqiang** [comment]
[Webkubect v1.6](https://github.com/webkubectl/webkubectl/releases/tag/v1.6) support kubectx and kubectl-aliases now. 😊

**Comment by ahmetb** [comment]
This project is super dope. I just tried. Thanks a bunch.
I might demo it at some point.
