### ISSUE TITLE
Allow to unset the current-context (-u?)

### ISSUE THREAD

**Issue by jorgemoralespou** [ahmetb/kubectx#185]
It would be nice if we could select current-context to empty, so unset the current-context, as for safety reasons, that would be similar (in effects) to logging off. This way, you can prevent commands being executed agains a cluster if any of the automation you're running does accidentally try to do something.

My workflow is similar to:
- going to work on something (login), so do `kubectx my-context`
- do my work
- finished working on a cluster (logout), so do `kubectx -off` (OR SIMILAR)

Using `kubectx -d <CTX>` does delete the context, but not unsets the current-context, so still has a value to a non existing context. What I'm requesting is the opposite, retain the context, but unset the value from current-context.

**Comment by ahmetb** [comment]
Does kubectx “” (empty string as arg) work?

**Comment by jorgemoralespou** [comment]
```
kubectx ""
error: empty context names are not allowed
```

**Comment by ahmetb** [comment]
@jorgemoralespou hmm looks like a this is a kubectl limitation. We primarily use kubectl to interact with kubeconfig, and never edit it directly (for a lot of reasons).

```
kubectl config set current-context ""
error: you cannot use set to unset a property
```

```
kubectl config use-context ""
error: empty context names are not allowed
```

It seems like kubectl can't do this. :(

On the other hand, given ~100k users we have and we're receiving this request for the first time, I'm inclined to think this is rather an exotic request. You can achieve what you want by setting something like KUBECONFIG=/dev/null in your shell.

**Comment by rsalmond** [comment]
@ahmetb the command you're looking for is `kubectl config unset current-context`

**Comment by rux616** [comment]
I actually just came here looking for the same thing. It could also be useful to have a flag to specify the fact that you want to unset the current context, maybe something like `-u`:

```
kubectx -u
```

**Comment by ahmetb** [comment]
Thanks, yeah I am currently still -1 for adding a feature for this to kubectx, need more evidence that this is a real user need (especially since kubectl can already do it).

**Comment by rux616** [comment]
> Thanks, yeah I am currently still -1 for adding a feature for this to kubectx, need more evidence that this is a real user need (especially since kubectl can already do it).

That's fair. I have just gotten used to manipulating my context through kubectx since it makes it much easier.

**Comment by rsalmond** [comment]
>kubectl can already do it

kubectl can already do `config use-context` too, I'm here for the shell sugar!

**Comment by jorgemoralespou** [comment]
Totally agree. I'm really surprised this has not come up before, as leaving the context set is almost as being always logged into the cluster. Any thing that we do might be executed on the current context/cluster we have set. 
I understand that many users don't work with multiple clusters, and that when you have PS1 indicating you the context you have selected is really obvious you want it set/unset when working/not working on stuff on the cluster.

**Comment by ahmetb** [comment]
I think simply, most users don't want to unset kubectl, because it leaves kubectl malfunctional. Most people dealing with multiple kubeconfig files can simply `unset KUBECONFIG` and get the same behavior. This is probably why it didn't come up before.

**Comment by rsalmond** [comment]
Yeah that is spot on. Leaving kubectl (and other `client-go` tools which understand kubeconfig) malfunctioning is precisely my use case. For those of us not using multiple config files unsetting the `current-context` is the next best thing.

**Comment by ahmetb** [comment]
After some thinking, I think I'm open to this.
Let's pursue this in #187 (it seems like we need to add integration tests and polish messages, readme etc).

**Comment by ktzsolt** [comment]
Just found out that this feature exists, just for the record, I really like it because I work with multiple clusters and multiple customers and it is mind easing to unset context after I finish a task in one environment so when I need to do something somewhere else I have to explicitly set the context back, so I can not run something on a different cluster (context) accidentally, so thank you.

It would be even better to have kubectx (and kubens too) be shell session aware.
