### ISSUE TITLE
fzf use should not be the default if installed on the host

### ISSUE THREAD

**Issue by prune998** [ahmetb/kubectx#188]
Why not only use FZF only when explicitely selected by something like `KUBECTX_USE_FZF=true` instead of having to set `KUBECTX_IGNORE_FZF=true` to disable it ?
 
It's a behaviour change that I really dislike, which I discovered when moving to zsh (from bash). 

Also, `kubectx -h` should list all this kind of behaviour and how to enable/disable them.
I could submit a PR if you think it's legit.

Thanks

**Comment by ahmetb** [comment]
Because this tool is designed for interactive use and this is how >100k existing users like it.
