### ISSUE TITLE
Feature request: Add passthrough of `--context` to kubens

### ISSUE THREAD

**Issue by deiga** [ahmetb/kubectx#190]
We're running multiple clusters and am switching between them very often. I also use aliasing to achieve switching between clusters with `--context`. Thus I would like to have `kubens` accept the `--context` flag so that I could easily switch namespaces in the different context I work in.

**Comment by ahmetb** [comment]
How would that be different than doing

```
kubectx A
kubens A1
kubectx B
kubens B1
kubectx A <- you're now in A1
```

I'm not sure why you'd want to change default ns of `A` to `A1` unless you're going to use it right away, which in that case you've probably done `kubectx A` already.

**Comment by deiga** [comment]
@ahmetb For the way I work `kubectx` is pretty much useless as I might need to look into multiple clusters during a few commands. I often have a `watch` or two running for different clusters as well. And whenever I do `kubectx` it changes the context _for every_ kubectl command I am running. Which is highly impractical.

I'd rather be doing:
```
kq ns A1
kq get ...
ks ns B1
ks get ...
kq get ... <- Again using A1
```

kq and ks are "aliases" for `kubectl "$@" --context ...`

**Comment by ahmetb** [comment]
I think you should continue to do what you're doing.
Both kubens and kubectx are designed to have side-effects.

**Comment by deiga** [comment]
@ahmetb But `kubens` doesn't have side effects, it just simply doesn't work if you are manually using `--context` or `--cluster` arguments from `kubectl`. Wouldn't it make sense that `kubens` can pass through essential arguments for connectin to a cluster, since it needs to connect to a cluster?

**Comment by ahmetb** [comment]
First of all, kubens is just a simple alias on top of kubectl (feel free to look at the source code, it's short).

The main user journey I've seen is that: User switches into a context (or they have only 1 context), then they switch into a namespace.

I understand that you might want to switch to a different namespace for a context, but I'm not getting why you're not switching into it in the first place, if you'll eventually end up running a command in that context.

If all your commands have `--context` I recommend you use kubectl directly, I probably won't add this to `kubens` to keep the interaction surface small & simple.

I estimate that this repo has over 100k users and the fact that it came up first time here makes me think we can live without this –and you can, too, by using `kubectl` directly to set namespace. :)

**Comment by deiga** [comment]
😂 I never even realized that I could set a namespace just with kubectl. Silly me 😂
