### ISSUE TITLE
Tried brew and manual installation, newest version doesn't seem to have valid autocomplete.

### ISSUE THREAD

**Issue by chris-lee-parsable** [ahmetb/kubectx#195]
Tried dozens of things but no matter what, brew or manual install this is what I get for autocomplete

$ _kubens
_arguments:comparguments:325: can only be called from completion function

$ _kubectx 
_arguments:comparguments:325: can only be called from completion function

Very saddening.

**Comment by ahmetb** [comment]
> Very saddening.

INDEED.

But it seems like it's actually working just fine for tens of thousands of people (including myself) who installed via `brew`. I believe the problem is on your setup. Are you using bash or zsh? At any rate, maybe see if other brew packages with autocompletions are working for you first.

**Comment by chris-lee-parsable** [comment]
@ahmetb , yea, I saw that in a thread, was debugging for a couple hours. The reason I posted is ALL my other auto-completions are working perfectly well. Which added to my frustration as well as lended slight credence that perhaps the issue was with kctx

**Comment by ahmetb** [comment]
I'm not even sure why/if calling `_kubectx` directly is supposed to work. I get the same error when I call it, but my tab completion works.

I assume you're using zsh: there has been several other ZSH completion issues (now closed) with solutions posted. Maybe take a look at those.

**Comment by chris-lee-parsable** [comment]
I did. None of them worked. It's a pity. Thanks for replying!

**Comment by chris-lee-parsable** [comment]
@ahmetb I updated my computer and did a hard restart over the weekend and now it all works. 

Weird as heck. Closing this, apologies for the trouble. Guess it must've just been some stupid thing that got cleared out when things were hard restarted.

**Comment by chris-lee-parsable** [comment]
Nevermind, kubectx works but kubens doesn't. But at this point it seems like my problem. Just weird.
