### ISSUE TITLE
Add command-line integration tests with bats

### ISSUE THREAD

**Issue by ahmetb** [ahmetb/kubectx#2]
We should use bats test framework and integrate travis CI to test many edge cases etc of the script.

I suspect bugs may be lurking (or occur later in refactoring) in env handling, switching back and forth, storing state etc

**Comment by feloy** [comment]
I would be happy to try and work at this

**Comment by ahmetb** [comment]
Also if you have a test plan (i.e. test cases you're planning to cover), please summarize here to discuss.

**Comment by doodlesbykumbi** [comment]
Feel free to edit this

## Test framework

- [ ] Based on bats
- [ ] Runs in Travis CI

## Test plan

It looks like @feloy has covered some of these but based on the help text of `kubectx`:

### Public interfaces
- [ ] list the contexts
- [ ] switch to context
- [ ] switch to the previous context
- [ ] rename context
- [ ] rename current-context
- [ ] delete context
- [ ] delete current-context
- [ ] help

### Unit test
- [ ] Enumerate all the functions in ./kubectx

**Comment by ahmetb** [comment]
I edited a bit. I think you entirely omitted the kubens, so if you can fill out that would be great!

Here's the kinds of things I added (mostly negative/edge cases):

- no kubectl detected (non-zero exitcode)
- list the contexts when no kubeconfig exists
- switch to the previous context, but there's no previous context
- delete non-existing context
- switch to non-existing context (non-zero exitcode)
- fails to retrieve list of namespaces (non-zero exitcode) --> kubens

I hope this gives a good idea about what I'm mainly looking for.

**Comment by pmartin-anevia** [comment]
@doodlesbykumbi on which tests do you prefer to work?

If you agree, you could work on the positive tests cases you listed in the plan, and I work on the negative/edge cases ones that Ahmet added.

**Comment by feloy** [comment]
Hi @ahmetb @doodlesbykumbi
This test plan sounds good to me.

About unit-testing the internal functions of kubectx and kubens, a problem is that the test script won't be able to source the kubectx/kubens scripts (to get the functions definitions) without executing the main part. A solution would be to cut these scripts to have a library one and a main one, but I'm not sure that would be a good experience for the user: having, as today, a single file for each command is very convenient

**Comment by feloy** [comment]
@doodlesbykumbi on which tests do you prefer to work?

If you agree, you could work on the positive tests cases you listed in the plan, and I work on the negative/edge cases ones that Ahmet added.

**Comment by ahmetb** [comment]
Let's set up the test infra first:

1. can you create a PR with a test/ dir, with one or two simple tests?
  - "kubectx -h" doesn't  fail
  - "kubens -h" doesn't fail
2. I'll create a PR adding travis CI with bats.

> a problem is that the test script won't be able to source the kubectx/kubens scripts

I'm not interested in unit-testing methods but rather the CLI tool itself. (I'll change the issue title.) So we should just invoke ../kubectx in the test.

**Comment by feloy** [comment]
@ahmetb ok, i'll create aPR with 2 simple tests for kubectx / kubens

**Comment by ahmetb** [comment]
BTW I looked at bats, last time I used it was around 2016. Around that time it was semi-maintained. Looks like it's entirely abandoned for now (last commit in 2016 and last release in 2014). 

If you know more interesting alternatives, I'd love to consider those before going all in on bats.

**Comment by ahmetb** [comment]
For studying how to write tests with bats, I have the following lengthy files still used after many years:

- https://github.com/Azure/custom-script-extension-linux/blob/master/integration-test/test/handler-commands.bats
- https://github.com/Azure/custom-script-extension-linux/blob/master/integration-test/test/basic.bats

One big recommendation is to do `echo "$output"` before testing anything –otherwise it'll just say test failed with no other indicator (like output) of failure.

**Comment by doodlesbykumbi** [comment]
Happy to have a go at kubens :) Should have a PR in a couple hours

**Comment by ahmetb** [comment]
> Well, here's a wall. We'd need to mock the Kubernetes API to carry out any non-trivial tests :(

Saw that coming!

I think we will need to override the $KUBECTL from the environment, then we can write a small bash script named mock-kubectl for the parts we need.

This part will refactoring to use the $KUBECTL if it exists in the environment. https://github.com/ahmetb/kubectx/blob/df557e4fa76238e00a71c96669c2b117caf0f896/kubectx#L176-L183

**Comment by feloy** [comment]
@doodlesbykumbi probably the kubectl command only, outputting a list of namespaces ("kubectl get namespaces" seems to be the only command used)

**Comment by doodlesbykumbi** [comment]
@feloy @ahmetb here's my attempt https://github.com/ahmetb/kubectx/pull/117

**Comment by ahmetb** [comment]
I think this now can be closed. Thanks a lot @feloy and @doodlesbykumbi.
