### ISSUE TITLE
Completion for Go binaries

### ISSUE THREAD

**Issue by apicht** [ahmetb/kubectx#206]
First, thanks for putting in the effort to release the Go version!

Have you considered bundling the completion scripts into the binaries, for usage similar to `kubectl completion bash`?

The reason I ask is that now I need to download the release binaries as well as the source code to get the completion scripts, which feels less than optimal.

**Comment by ahmetb** [comment]
We already have completion for bash script implementations. It’s very likely I’ll keep those as the completion scripts.

Note that the manual download situation with Go implementation is temporary, eventually we’ll swap out however you’re getting kubectx normally (e.g Homebrew) so the completion scripts will be there.
