### ISSUE TITLE
homebrew install is broken

### ISSUE THREAD

**Issue by caarlos0** [ahmetb/kubectx#207]
https://github.com/Homebrew/homebrew-core/pull/54002/files

it seems to be still installing the scripts...

**Comment by ahmetb** [comment]
It's expected to still install the bash scripts.
See release notes https://github.com/ahmetb/kubectx/releases

**Comment by arbourd** [comment]
Should we start installing the Go binary now?

**Comment by ahmetb** [comment]
> Should we start installing the Go binary now? I'm willing to patch it. Just not sure what the restriction is based on the above note.

Shouldn't need to switch to the Go binary yet. That's just about completion scripts Homebrew is installing.
