### ISSUE TITLE
Homebrew formula still depends on kubernetes-cli

### ISSUE THREAD

**Issue by dsiebel** [ahmetb/kubectx#208]
I don't know if this is the right place to report, but I could not figure out who maintains the Homebrew formula for kubectx and I thought it might be worth mentioning:
The `kubectx` Homebrew formula for 0.9.0 still depends on `kubernetes-cli`:
https://github.com/Homebrew/homebrew-core/blob/master/Formula/kubectx.rb#L10
although the release page states
> kubectx/kubens no longer depends on kubectl

Besides that, the new version seems to work like a charm, good job! 😃

**Comment by dsiebel** [comment]
My bad, apparently the formula still installs the bash version, despite it being 0.9.0. Closing.

**Comment by ahmetb** [comment]
Yes, this is by design.
Go version is not ready for prime time usage yet. It's better homebrew stays on bash version for now.
