### ISSUE TITLE
Could be great if you could add auto switch / activate proxy when running kctx

### ISSUE THREAD

**Issue by roeera** [ahmetb/kubectx#21]

**Comment by ahmetb** [comment]
I'm not sure what you mean by proxy. Can you please explain in a little bit more detail?

**Comment by roeera** [comment]
When you manage few clusters, each time you switch content and wants to reach dashboard you need to run : kubectl proxy &
It would be great, when you run kctx to switch content if it automatically kill old proxy, and recreate it for the new switched cluster.
Not so complicated but very very useful.
Let me know if something is still unclear

**Comment by ahmetb** [comment]
Got it now. It sounds like it's kind of out of scope for this project. I'm not sure how many people have a workflow like that. It's the first time I am hearing about it.

**Comment by roeera** [comment]
This is very basic usage in order to reach dashboard.
You can check this scenario via kubernetes dashboard repo.
From my point of view this feature would be great and I would add this via
flag or something.

**Comment by ahmetb** [comment]
I think this creates unnecessary coupling and probably should be solved at kubectl (i.e. a hook when context changes). I bet it won't happen anytime soon and [kubectl plugins](https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/) might actually open up a way to do that in the future. (i.e. wrap the set-context command and execute your hook).

I have a simpler solution for you, however:

You should use [entr(1)](http://entrproject.org/) to watch `$HOME/.kube/config` file changes (it changes when you change contexts on kubectl). It's as simple as:

    entr ./your_script.sh <<< $HOME/.kube/config
