### ISSUE TITLE
kubens select and switch take too long

### ISSUE THREAD

**Issue by aduong** [ahmetb/kubectx#216]
When using `kubens $ns` and `kubens -`, it's taking over ten seconds. This is caused by the relisting of namespaces, of which I have at least thousands. It'd be nice if this could be sped up, either by allowing me to disable the existence check or caching the namespaces.

**Comment by ahmetb** [comment]
Oh man you might be the only person with thousands of namespaces. This sounds a lot like #83 which is reinforcing the point that we should probably implement.

**Comment by aduong** [comment]
#83 is similar, but I do have permissions to list namespaces and I appreciate autocomplete, interactive listing & choosing (via fzf) every so often. Here are some concrete cases where I don't need the namespace check:
* Using a `kubens X` from my shell history. The check has already been done in the past and generally namespaces don't get deleted.
* Using `kubens -`

I think one possible tweak is to replace the list check with a get check, i.e. instead of `grep -q ^"${1}"\$ <(get_namespaces)`, do a `$KUBECTL get namespace "${1}"` and interpret the result/status of that.

**Comment by ahmetb** [comment]
Yeah, that makes perfect sense. It's likely we’ll fix this in the Go implementation. So I recommend you fork the bash implementation and use yourself in the meanwhile. Thanks for bringing it up.
