### ISSUE TITLE
Color formatting does not work on Windows Command Prompt

### ISSUE THREAD

**Issue by kylelaverty** [ahmetb/kubectx#226]
### Issue:
When using commands like `kubens` and `kubens newnamespace` in a windows cmd terminal, the output is shown but the part that is supposed to represent the color setting is not being sent correctly to the terminal and is instead being rendered out as text.

*Command Prompt Output*
```
C:\Users\username>kubens
default
[32;1musername[0m
kube-node-lease
kube-public
kube-system
```
*Command Prompt Screenshot*
![image](https://user-images.githubusercontent.com/12103001/82455810-62f67880-9a81-11ea-985b-a2bc3bbb39fc.png)

### Steps to Reproduce:
* Use Windows 10 (Version is 10.0.18363.815 as reported by the command prompt)
* Open Command Prompt (normal or Admin)
* Run `kubens`

### Expected Result
It appears it is trying to color the username namespace as green to represent which one is the default namespace.

**Comment by ahmetb** [comment]
This is already fixed (see recently closed issues) but I need to make a release available. Thanks.

**Comment by kylelaverty** [comment]
Sorry about that, I didn't mean to double report.
