### ISSUE TITLE
Make kubectx switch https_proxy when context is switched

### ISSUE THREAD

**Issue by boredabdel** [ahmetb/kubectx#231]
I'm working on a project where i interact with multiple clusters, all have private masters and have a k8s_proxy deployed in each cluster, each time i switch context with kubectx i also have to export the proper https_proxy IP:PORT. I wrapped everything in bash but it would be great if you can somehow tell kubectx which proxy is associated to which context and let it export the proper proxy for the cluster you are switching context to

**Comment by boredabdel** [comment]
I open this issue to explore how easy that would be to do, happy to contribute the feature !

**Comment by ahmetb** [comment]
Sadly as you can imagine setting https_proxy is out of scope for this project. Feel free to fork and adapt.
