### ISSUE TITLE
Proposal: Add support for Rancher CLI

### ISSUE THREAD

**Issue by juanmancebo** [ahmetb/kubectx#238]
## Abstract

Add support for `Rancher CLI` when switch context with `kubectx`.

## Background

A team with multiple `Kubernetes` clusters managed by `Rancher` that uses `kubectx` have to change the rancher context manually after the execution of `kubectx` switch context. With this new feature, both context are changed inside `kubectx`.
 
## Proposal

Adding support for switch `Rancher` context at the same time as the `Kubernetes` context are changed.

**Comment by ahmetb** [comment]
Unfortunately this is out of scope for us. 
It could be if Rancher was reading from the same kubeconfig —or Rancher was a wrapper around kubectl like “oc” command of OpenShift (we could allow customizing $KUBECTL in terms of which cmd to run). 
But this is far too specific to be here and I don’t use Rancher, so maintenance is going to be a problem as well. 

I am inclined to turn this down.

**Comment by juanmancebo** [comment]
I see. Sadly rancher cli isn't a wrapper of kubectl :(
