### ISSUE TITLE
[Go] kubens failed to load previous namespace on Windows

### ISSUE THREAD

**Issue by TrentScholl** [ahmetb/kubectx#244]
I am using kubens v0.9.0 on Windows and when trying to switch to a namespace, the following error is printed.

`error: failed to load previous namespace from file: open C:\Users\Trent Scholl\.kube\kubens\arn:aws:eks:ap-southeast-2:xxxxxxxxxxxx:cluster\cluster-name: The filename, directory name, or volume label syntax is incorrect.`

This appears to be due to the colon in the cluster name (which is default when using the aws cli to update kube config for eks clusters)

**Comment by ahmetb** [comment]
Yep this was fixed in master. I will do a release soon.
