### ISSUE TITLE
kubens & kubectx error when pressing tab | using go binary

### ISSUE THREAD

**Issue by MeenachiSundaram** [ahmetb/kubectx#246]
pressing tab i'm getting the below error
```
$ kubens
(eval):1: _kubens: function definition file not found
(eval):1: _kubens: function definition file not found
(eval):1: _kubens: function definition file not found

$ kubectx
(eval):1: _kubectx: function definition file not found
(eval):1: _kubectx: function definition file not found
(eval):1: _kubectx: function definition file not found
```

Giving the correct name it is working
```
$ kubectx s**-***
✔ Switched to context "s**-****".
```

**Comment by ahmetb** [comment]
How did you install? Which shell?

**Comment by MeenachiSundaram** [comment]
I'm using MacOS
![Screen_Shot_2020-07-30_at_10_09_53_AM](https://user-images.githubusercontent.com/17172466/88898460-0cf63c00-d24d-11ea-8c6d-409e6267bd82.png)

and downloaded kubectx and kubens from Release page and copied to path
https://github.com/ahmetb/kubectx/releases/download/v0.9.1/kubectx_v0.9.1_darwin_x86_64.tar.gz
https://github.com/ahmetb/kubectx/releases/download/v0.9.1/kubens_v0.9.1_darwin_x86_64.tar.gz

```
❯ which kubectx
/usr/local/bin/kubectx

❯ which kubens
/usr/local/bin/kubens
```

**Comment by ahmetb** [comment]
So this sounds like a zsh issue to me. I'm using zsh too, and not having problems. I install it myself via Homebrew. Unless you explicitly install the completion files, this would not work.
