### ISSUE TITLE
kubectx error loading config

### ISSUE THREAD

**Issue by dvikram** [ahmetb/kubectx#248]
On Mac installed with brew v0.9.0, using zsh

On setup, everything works fine on the initial iTerm window. I am able to switch between cluster and different namespaces.

> (⎈ |clu0:ns1)➜  ~

But when I open up a new iTerm window. I get this error -

> (⎈ |N/A:N/A)➜  .kube kubectx clu0
error loading config file "/Users/Vikram/.kube/kubens/clu0": couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
error loading config file "/Users/Vikram/.kube/kubens/clu1": couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
error getting current context
(⎈ |N/A:N/A)➜  .kube cat /Users/Vikram/.kube/kubens/clu0
ns1%                                                                                                             
(⎈ |N/A:N/A)➜  .kube cat /Users/Vikram/.kube/kubens/clu1
default%

To make it work, I need to delete all the files from kubens directory.

**Comment by ahmetb** [comment]
I think you accidentally set the files in $HOME/.kube/kubens directory in your KUBECONFIG environment variable somehow. That file is supposed to be a very small text file; but your kubectl is parsing it as kubeconfig. I bet `kubectl` was failing in the same window. I don't think this happens to others.
