### ISSUE TITLE
Globbing/Wildcard support for -d

### ISSUE THREAD

**Issue by rbo** [ahmetb/kubectx#249]
First of all: Thanks for the awesome tool. I really appreciate the rewrite in Go, easy to install in systems without any root privileges or package manager access. 

I have one little feature request: I would like run following command to delete all matching contexts: `kubectx -d migration-demo-1592*` 

Work-a-round: `kubectx |grep migration-demo-1592 | xargs kubectx -d` 

Thanks

**Comment by ahmetb** [comment]
I believe that’s how most unix tooling work, you can put tools together that way. Globbing is a rare use case, so we most likely wouldn’t implement. 

Also, when you type * in your shell, it is evaluated on local files and doesn’t get passed to the program.
