### ISSUE TITLE
Proposal: Offer ppc64le arch release binary

### ISSUE THREAD

**Issue by runlevel5** [ahmetb/kubectx#252]
IBM / Red Hat has been behind the OpenPOWER initiative with support for K8S on PowerPC64 LE architecture.

I have been running K8S on Ubuntu Bionic PPC64LE for nearly 2 months and it's just as good as that of x86_64. It would be nice if kubectx and kubens could offer the binary for ppc64le so that users do not have to compile everything from source.

**Comment by ahmetb** [comment]
What’s the os/arch pair of this in Go. We can add.

**Comment by runlevel5** [comment]
> What’s the os/arch pair of this in Go. We can add.

`linux/ppc64le` please

**Comment by ahmetb** [comment]
I made the commit, you can get the binaries by running `GOOS=linux GOARCH=ppc64le go build ./cmd/kubectx` locally or `goreleaser build --rm-dist --skip-validate` locally.

I'm not sure when I'll make a new release (probably in a few months). That's when it'll be available on the Releases page of this repo.

**Comment by ahmetb** [comment]
Also I forgot to ask: What's your installation method? Do you use any package manager or is it wget/curl?

**Comment by runlevel5** [comment]
@ahmetb I simply git clone and compile from the source.
