### ISSUE TITLE
warning: kubeconfig file not found for Go binaries

### ISSUE THREAD

**Issue by Gerrit-K** [ahmetb/kubectx#253]
I just tried out the new Go binaries and I'm getting a warning (and no results) when I simply execute them without arguments. Instead I was expecting the fzf selection to pop up as the shell scripts previously did.

If I explicitly call the command with an argument, e.g. `kubens default` I'm seeing this error:
```
error: kubeconfig error: failed to load: kubeconfig file not found: open /Users/<me>/.cache/.kube/config: no such file or directory
```

If I run `KUBECONFIG=~/.kube/config kubens default` it works. 

I'm guessing that the Go binaries are not looking for a config file in the default location (`$HOME/.kube/config`) but rather fall back to `$XDG_CACHE_HOME/.kube/config` which in my case is `$HOME/.cache/kube/config`.

**Comment by ahmetb** [comment]
> I'm guessing that the Go binaries are not looking for a config file in the default location ($HOME/.kube/config) but rather fall back to $XDG_CACHE_HOME/.kube/config which in my case is $HOME/.cache/kube/config.

Very unlikely, as it works on my machine with the default path and we have integration tests giving it a custom kubeconfig path. 

As far as I know, client-go doesn’t look at XDG dirs at all, let alone _CACHE. kubeconfig file isn’t a temporary/cache artifact. https://github.com/kubernetes/client-go/blob/master/tools/clientcmd/loader.go#L141

**Comment by Gerrit-K** [comment]
Thanks for the quick response. You're right. Unsetting `XDG_CACHE_HOME` doesn't change anything either. Do you have any suggestions on how I can debug this or any further information I should provide?

The environment is MacOS Catalina, kubectx/kubens binaries are from the latest release page.

**Comment by ahmetb** [comment]
Do you set XDG_ vars yourself? Afaik, they aren’t a thing on macOS. 

I search for ".cache/.kube/config" on Google, it’s not really a thing even as an error message that happens to others. :-/

**Comment by ahmetb** [comment]
Btw you are right we do take a look at XDG_ CACHE_HOME. https://github.com/ahmetb/kubectx/blob/master/internal/cmdutil/util.go

I have to understand why it got there as I believe client-go loading rules don’t have it.

**Comment by ahmetb** [comment]
I believe the fact that we read XDG_CACHE_HOME was carried over from the bash implementation(s), which did:

    KUBECTX="${XDG_CACHE_HOME:-$HOME/.kube}/kubectx"

but that wasn't meant for "loading kubeconfig"; it was for "storing our cached data".

I now see that we use that to determine default KUBECONFIG path (if set) as well. I'm opening issue https://github.com/ahmetb/kubectx/issues/254 to track this.

Now I'm suspecting you haven't fully unset the XDG_CACHE_HOME perhaps?

**Comment by Gerrit-K** [comment]
> Do you set XDG_ vars yourself? Afaik, they aren’t a thing on macOS. 
> 
> I search for ".cache/.kube/config" on Google, it’s not really a thing even as an error message that happens to others. :-/

Oh okay, didn't know that. I am using linux for a long time and just copied my dotfiles to a Mac last week. And yes, the `.cache` part is from my `XDG_CACHE_HOME`, but the `.kube/config` part is not in my dotfiles.

> I'm opening issue #254 to track this.

Great, I'll keep an eye on it, thanks!

> Now I'm suspecting you haven't fully unset the XDG_CACHE_HOME perhaps?

Indeed! Unsetting it manually turned out to be not enough as it was set in my `.zshenv`. If I remove it there, the command works 👏 

Only thing that's still bugging me are the color escape sequences, but I'm going to create another issue for that as it's most likely unrelated.
