### ISSUE TITLE
Unable to use kubens with EKS on Windows

### ISSUE THREAD

**Issue by bnau** [ahmetb/kubectx#255]
Hello all,

I just used kubectx to switch to an EKS cluster. Now, when I use kubens, I have the following error:
`failed to load previous namespace from file: open C:\Users\USERNAME\.kube\kubens\arn:aws:eks:REGION:CLUSTER_ID:cluster\CLUSTER_NAME`

I guess it's because directories can't have colons in their names on Windows.

**Comment by ahmetb** [comment]
This was fixed. Are you using v0.9.1?

**Comment by bnau** [comment]
I just upgraded to 0.9.1 and it's working fine.
Thank you
