### ISSUE TITLE
Rename Completions Scripts for ZSH to Start with Underscore

### ISSUE THREAD

**Issue by jGleitz** [ahmetb/kubectx#262]
If the completion scripts started with `_`, it would be easy to install them with [antibody](https://getantibody.github.io). Simply adding 

```
ahmetb/kubectx path:completion kind:fpath
```

to `~/.zshplugins.txt` would be enough (depending on the setup, one would still need to call `compinit` in `~/.zshrc`.

This would give users a nice and easy way to install the completion script if they are already using antibody.

**Comment by ahmetb** [comment]
I'm supportive, I think it might require some changes on the homebrew formula as well. (And probably alpine/debian distributions we currently have outside this repo.)

**Comment by chiefy** [comment]
I'm using [zsh-snap](https://github.com/marlonrichert/zsh-snap) and having the same issue. I changed the filenames to `_kubectx` and `_kubens` and the autoloading works fine. Thanks.
