### ISSUE TITLE
support for macOS Big Sur 11.x

### ISSUE THREAD

**Issue by jpoley** [ahmetb/kubectx#276]
It would be great to get core support for new macOS

Error: Your CLT does not support macOS 11.0.
It is either outdated or was modified.
Please update your CLT or delete it if no updates are available.
Error: An exception occurred within a child process:
  SystemExit: exit

**Comment by ahmetb** [comment]
Are you on new M1 ARM-based architecture or i386-64?

What’s your installation method?

**Comment by jlaamanen** [comment]
Had the same problem (Intel machine), but it was an issue with outdated CommandLineTools (CLT), as the error message is saying. Install worked fine after uninstalling old CLT and installing new ones:
```sh
sudo rm -rf /Library/Developer/CommandLineTools/
sudo xcode-select --install
```

**Comment by Andrewpk** [comment]
> Had the same problem with Homebrew (Intel machine), but it was an issue with outdated CommandLineTools (CLT), as the error message is saying. Install worked fine after uninstalling old CLT and installing new ones:
> 
> ```shell
> sudo rm -rf /Library/Developer/CommandLineTools/
> sudo xcode-select --install
> ```

I had the same issue on an intel mac except was using fully up-to-date Xcode (12.4) and Command Line Tools (12.4) that I confirmed worked with macOS 11.2.3. It sounds like this could be a problem with kubectx install.

**Comment by ahmetb** [comment]
v0.9.3 provides darwin/arm64 release.This probably should be resolved? If not let me know.
