### ISSUE TITLE
error on windows 10

### ISSUE THREAD

**Issue by andreyza-tr** [ahmetb/kubectx#278]
windows 10 with CMDER shell, with GO installed, AZURE AKS cluster:

λ kubens
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x1115be7]

goroutine 1 [running]:
k8s.io/client-go/plugin/pkg/client/auth/azure.(*azureTokenSource).storeTokenInCfg(0xc000043900, 0xc00015e6e0, 0xd, 0xc00015e6e0)
        /home/runner/go/pkg/mod/k8s.io/client-go@v0.17.0/plugin/pkg/client/auth/azure/azure.go:276 +0x397
k8s.io/client-go/plugin/pkg/client/auth/azure.(*azureTokenSource).Token(0xc000043900, 0x0, 0x0, 0x0)
        /home/runner/go/pkg/mod/k8s.io/client-go@v0.17.0/plugin/pkg/client/auth/azure/azure.go:194 +0x45a
k8s.io/client-go/plugin/pkg/client/auth/azure.(*azureRoundTripper).RoundTrip(0xc000088e80, 0xc00022c300, 0x13e1398, 0xa, 0xc0002bca40)
        /home/runner/go/pkg/mod/k8s.io/client-go@v0.17.0/plugin/pkg/client/auth/azure/azure.go:125 +0x88
k8s.io/client-go/transport.(*userAgentRoundTripper).RoundTrip(0xc000088ea0, 0xc00022c200, 0xc000088ea0, 0x0, 0x0)
        /home/runner/go/pkg/mod/k8s.io/client-go@v0.17.0/transport/round_trippers.go:159 +0x1c7
net/http.send(0xc00022c200, 0x1584660, 0xc000088ea0, 0x0, 0x0, 0x0, 0xc0000068b0, 0x2030000, 0x1, 0x0)
        /opt/hostedtoolcache/go/1.14.4/x64/src/net/http/client.go:252 +0x445
net/http.(*Client).send(0xc0004828a0, 0xc00022c200, 0x0, 0x0, 0x0, 0xc0000068b0, 0x0, 0x1, 0xc0002bc6e0)
        /opt/hostedtoolcache/go/1.14.4/x64/src/net/http/client.go:176 +0x101
net/http.(*Client).do(0xc0004828a0, 0xc00022c200, 0x0, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.14.4/x64/src/net/http/client.go:699 +0x451
net/http.(*Client).Do(...)
        /opt/hostedtoolcache/go/1.14.4/x64/src/net/http/client.go:567
k8s.io/client-go/rest.(*Request).request(0xc0004d10e0, 0xc0004c1830, 0x0, 0x0)
        /home/runner/go/pkg/mod/k8s.io/client-go@v0.17.0/rest/request.go:801 +0x3f0
k8s.io/client-go/rest.(*Request).Do(0xc0004d10e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/runner/go/pkg/mod/k8s.io/client-go@v0.17.0/rest/request.go:873 +0xdf
k8s.io/client-go/kubernetes/typed/core/v1.(*namespaces).List(0xc0002b8ac0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/runner/go/pkg/mod/k8s.io/client-go@v0.17.0/kubernetes/typed/core/v1/namespace.go:86 +0x17e
main.queryNamespaces(0xc000127e68, 0xc0002c3e40, 0xc, 0x13df3a9, 0x7, 0x0)
        /home/runner/work/kubectx/kubectx/cmd/kubens/list.go:64 +0x24a
main.ListOp.Run(0x1583fe0, 0xc000070140, 0x1583fe0, 0xc000070190, 0x0, 0x0)
        /home/runner/work/kubectx/kubectx/cmd/kubens/list.go:36 +0x209
main.main()
        /home/runner/work/kubectx/kubectx/cmd/kubens/main.go:21 +0x116

the kubens --help works  =)

**Comment by ahmetb** [comment]
See #240.
