### ISSUE TITLE
When switching between contexts run custom bash commands for login to the cluster

### ISSUE THREAD

**Issue by jakuboskera** [ahmetb/kubectx#280]
We have multiple k8s clusters and for each cluster its own API server for login - dev, staging, production. When I want to work with some cluster I have to login through API server before. For example I want work with dev cluster = I login to against dev API server and then I am able to work with dev cluster, but now I want to now work with cluster staging, so I have to login again through staging API server and then I am able to work with staging cluster. So the workflow is little bit annoying. The login is consitents of just two basic bash commands. My idea is what about to use kubectx for switching between clusters (contexts), but before switch use some custom commands for login. So after I could use just kubectx for switching between contexts (clusters) with automatically login.

**Comment by ahmetb** [comment]
I'd recommend you fork the `kubectx` script and adapt for your needs.

**Comment by jakuboskera** [comment]
Thanks for advice, I did the change according my needs.
