### ISSUE TITLE
kubens doesn't support clusters using SOCKS5 'proxy-url'

### ISSUE THREAD

**Issue by peterporter** [ahmetb/kubectx#284]
When routing to my Kubernetes cluster via SOCKS5 proxy, I receive the following error when attempting to query namespaces or select a different namespace:

```
error: could not list namespaces (is the cluster accessible?): failed to list namespaces from k8s API: 
Get "https://rancherapi.xyz.abc.internal:6443/api/v1/namespaces?limit=500": dial tcp 55.44.33.22:6443:
 connect: connection refused
```

My ~/.kube/config file is configured using the 'proxy-url' setting as follows:

```
  - cluster:
        certificate-authority-data: xxx
        server: https://rancherapi.xyz.abc.internal:6443
        proxy-url: socks5://localhost:1234
    name: rancher
```

**Comment by ahmetb** [comment]
(I'm assuming you're using the Go-based implementation of kubens). This likely needs some debugging. Technically we use the same client library as kubectl does (k8s.io/client-go) but there's a chance that the library doesn't parse the proxy config from KUBECONFIG file properly when used by itself. 🤔

I don't have the time to debug this one but help is welcome at this time.

**Comment by ahmetb** [comment]
Or actually this could be simply because `kubens` uses client-go version 0.17.0 (which targets the Kubernetes 1.17.0), but the `proxy-url` option was introduced in Kubernetes 1.19 https://github.com/kubernetes/client-go/issues/351#issuecomment-626789979 in that case we can simply fix it and make a release.

**Comment by ndisidore** [comment]
Pulling down master and building locally worked for me, so can confirm the update to client-go was enough to do the trick :1st_place_medal:

**Comment by ahmetb** [comment]
OK I'll do a release soon.

**Comment by ahmetb** [comment]
We have releases now.
/close
