### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by dkirrane** [ahmetb/kubectx#29]
Would love to see Windows executables similar to kubectl and helm.
`kubectx.exe` and `kubens.exe`

**Comment by ahmetb** [comment]
@dkirrane it's written in bash, I have no immediate plans to rewrite. It's _probably_ possible to write these in powershell, but I’m not a big fan of maintaining two implementations (also not a big fan of converting this to a Go or a Python program which requires installing extra stuff). 

If you consider using "Git Bash" shell or even better, the so-called Ubuntu on Windows which brings the Windows Subsystem for Linux (WSL) and therefore native bash support, kubectx/kubens should work.

**Comment by thomasliddledba** [comment]
I don't know if this is useful but I created a Windows version of kubectx.  I love this tool and I do alot of k8s administrator using my Powershell and Commandline prompts.  Kubectx is an awesome tool!
https://github.com/thomasliddledba/kubectx

**Comment by ahmetb** [comment]
@thomasliddledba Please do not use the same name.

**Comment by thomasliddledba** [comment]
That's absolutely fair  Sorry about that.  Would you mind if something like kubectxwin?  I want to make sure I'm not stepping on your toes at all.

**Comment by ahmetb** [comment]
kubectxwin or -windows sounds fine.

**Comment by thomasliddledba** [comment]
Awesome - I will do that.  Thank you so much.  This is a great idea/tool.

**Comment by dkirrane** [comment]
@ahmetb tried script GitBash but hitting this:
```
$ kubectx
character set not supported
error: you did not choose any of the options
```

**Comment by ahmetb** [comment]
@dkirrane can you run with `DEBUG=1 kubectx` ?

**Comment by dkirrane** [comment]
Done https://github.com/ahmetb/kubectx/issues/88

**Comment by SumanGitHub** [comment]
FYI:  Tried **kubectxwin** in windows server 2016, it **worked** .  Thanks
