### ISSUE TITLE
Password protect / timeout feature for context?

### ISSUE THREAD

**Issue by ameeno** [ahmetb/kubectx#290]
Hiya.

Perhaps this is slightly out of scope for a context switcher.

but I accidentally made a big blunder and dodged a massive bullet running dangerous commands in prod that was intended to be run against the lab.

Is there any idea's you have or any features you could add that would password protect particular context's or timeout a particular context and then auto switch back to default?

It would save me a ton. I need access to the prod context for some work-related tasks, but as I use ctx as a quick switcher, perhaps there should be a protection/security mechanism for certain contexts (like safety gloves) 

what do you think?

**Comment by ahmetb** [comment]
Out of context indeed.  You can hack your own bash function around if you like. We can't tell what's prod and what's not and the problem you described isn't specific to kubectx. People make these mistakes with kubectl as well. You can use a plugin like "kubectl-prompt" maybe.
