### ISSUE TITLE
Add Mac M1 build

### ISSUE THREAD

**Issue by cagataygurturk** [ahmetb/kubectx#291]
Title is clear :)

**Comment by ahmetb** [comment]
Can you test the binary if I provide one?

**Comment by cagataygurturk** [comment]
Of course I can

**Comment by ahmetb** [comment]
Please try out the binary at https://github.com/ahmetb/kubectx/releases/tag/v0.9.3.

For the time being, both Homebrew and Krew distributions use the old bash-based implementation (as that’s intended). In the future, we’ll be packaging and distributing the binaries instead.

**Comment by cagataygurturk** [comment]
Works like a charm :) Sagol!
