### ISSUE TITLE
Infinite loop error when setting kubectx to be an alias on ~/.bash_profile

### ISSUE THREAD

**Issue by kamok** [ahmetb/kubectx#296]
To replicate, add an alias such as the one below to ~/.bash_profile

```
alias local='kubectx docker-desktop'
```

Then, when you do `source ~/.bash_profile` you will get the below infinite loop error:

```
error: too many arguments
USAGE:
  kubectx                       : list the contexts
  kubectx <NAME>                : switch to context <NAME>
  kubectx -                     : switch to the previous context
  kubectx -c, --current         : show the current context name
  kubectx <NEW_NAME>=<NAME>     : rename context <NAME> to <NEW_NAME>
  kubectx <NEW_NAME>=.          : rename current-context to <NEW_NAME>
  kubectx -d <NAME> [<NAME...>] : delete context <NAME> ('.' for current-context)
                                  (this command won't delete the user/cluster entry
                                  that is used by the context)
  kubectx -u, --unset           : unset the current context

  kubectx -h,--help             : show this message
error: too many arguments
error: too many arguments
USAGE:
  kubectx                       : list the contexts
  kubectx <NAME>                : switch to context <NAME>
  kubectx -                     : switch to the previous context
  kubectx -c, --current         : show the current context name
  kubectx <NEW_NAME>=<NAME>     : rename context <NAME> to <NEW_NAME>
  kubectx <NEW_NAME>=.          : rename current-context to <NEW_NAME>
  kubectx -d <NAME> [<NAME...>] : delete context <NAME> ('.' for current-context)
                                  (this command won't delete the user/cluster entry
                                  that is used by the context)
  kubectx -u, --unset           : unset the current context

  kubectx -h,--help             : show this message
error: too many arguments
```

**Comment by kamok** [comment]
Replicate on mine and my co-worker's Mac. I'm on Catalina and he's on Big Sur.

**Comment by ahmetb** [comment]
Go implementation or Bash implementation?

**Comment by kamok** [comment]
I have to guess Go?

```
brew list --versions kubectx
kubectx 0.9.3
```

**Comment by ahmetb** [comment]
Can you follow the symlink? I think that is the bash version. I appreciate if you can try the Go version.

**Comment by kamok** [comment]
Sorry I'm not follow what you mean by symlink. Can you tell me how I can check if I'm on the Go version or Bash version? I just did `brew install kubectx`.

**Comment by kamok** [comment]
Ok I did `readlink kubectx` and see that it's in `/Cellar/kubectx/0.9.3/bin`, which indeed is Bash. I'll try the Go version

**Comment by kamok** [comment]
I downloaded the 0.9.3 from Releases, I put it into `/Cellar/kubectx/0.9.3/bin`, and moved the Bash execuetable from Homebrew into a different folder. I'm still getting some sort of error when I do `source ~/.bash_profile`.

```
$ source ~/.bash_profile
error: too many arguments
error: too many arguments
error: too many arguments
error: too many arguments
error: too many arguments
stat: : stat: No such file or directory
error: too many arguments
error: too many arguments
error: too many arguments
error: too many arguments
error: too many arguments
error: too many arguments
error: too many arguments
stat: : stat: No such file or directory
error: too many arguments
error: too many arguments
error: too many arguments
error: too many arguments
error: too many arguments
error: too many arguments
error: too many arguments
stat: : stat: No such file or directory
error: too many arguments
error: too many arguments
error: too many arguments
error: too many arguments
error: too many arguments
error: too many arguments
error: too many arguments
```

**Comment by kamok** [comment]
Also I love how fast the Go implementation is BTW. So great! Would not have known about it if I didn't report the bug.

**Comment by ahmetb** [comment]
We'll eventually switch to Go version but not sure why your bashprofile is not behaving.
Maybe try replacing the linked script directly with the binary.

**Comment by kamok** [comment]
I directly moved the downloaded binary into `/usr/local/bin`. Works fine. But source bash_profile still has same issue. It seems to be a problem in both Go and Bash implementation.

Is nobody else using alias with kubectx? Or is there something else in my bash_profile that's causing an issue?

**Comment by ahmetb** [comment]
The infinite loop issue might be a problem with your bash version or bashrc/bash_profile file. Can you repro with another alias that has 2 arguments (but doesn't use kubectx)?
