### ISSUE TITLE
Add kubectx/kubens list subcommand

### ISSUE THREAD

**Issue by Knappek** [ahmetb/kubectx#297]
First of all, thanks a lot for this project, it is awesome! 🎉 

In order to list contexts, you usually only have to type `kubectx` according to the help message. But if there is fzf running it will obviously not list all contexts but opens an interactive session in order to choose a context.

Therefore I would like to suggest to add a list subcommand with that you can type `kubectx --list` (or short `kubectx -l`) in order to list contexts. I know you can also achieve that with `kubectx | cat` but I would prefer to have a simple command for that (typing `-l` is easier than `| cat`). 
Same applies to `kubens`.

Does this make sense? If so, I would also be open to add this feature and open a PR if you are fine with it.

**Comment by ahmetb** [comment]
I think this has come up several times. Can you please search the closed issues for the reasoning? Kubectl has a native command that does this, and the use cases are limited. And non-fzf users will be confused. So I think it doesn't add enough value but takes up more space. Not to mention it results in 2 ways of doing the same thing for non-fzf users.
