### ISSUE TITLE
Feature Request: Add context 

### ISSUE THREAD

**Issue by alexanderturner** [ahmetb/kubectx#298]
Most Kubeconfig's are distributed as whole files. It would be awesome if there was a flag in kubectx to add a context with a path to a file, that'll merge it into your existing Kubeconfig file - or a kubectx specific file.

**Comment by ahmetb** [comment]
We're not trying to do everything in this little tool.
But you can learn how to do that by reading https://ahmet.im/blog/mastering-kubeconfig/.
