### ISSUE TITLE
Rename kubectx

### ISSUE THREAD

**Issue by pieterlange** [ahmetb/kubectx#3]
If the project goal is to save keystrokes, `kubectx` is inconvenient because it breaks autocompletion to `kubectl`.

(i'd have to enter `kub<tab>l<space>`)

**Comment by ahmetb** [comment]
Any suggestions?

I personally aliased kubectl to k, so I don't see this problem.

**Comment by rfay** [comment]
Agreed, absolutely the only thing I don't like about this lovely tool :)

How about kctx ? kcontext?

**Comment by pieterlange** [comment]
`ktctx` would be better from a autocompletion perspective. i'd choose `kontext` from a marketing perspective. but thats up to the author

**Comment by ahmetb** [comment]
Purely from the marketing aspect, I actually tend to keep it as `kubectx`. In fact, I'm planning to add a new accompanying command called `kubens` (#1) .

I wish `brew link` had a way of aliasing the command easily so that you all could personalize. I will keep this discussion open to gather more feedback. Perhaps we can switch to `kctx`/`kns` someday.

**Comment by jwhitcraft** [comment]
@ahmetb 

kinda of off topic, since you aliased k to kubectl do you have bash completion working, I can't figure out how to make the completion work for the alias of k.

i have this, but it doesn't work

```
alias k='kubectl'
source <(kubectl completion bash)
complete -o default -F __start_kubectl k
```

**Comment by ahmetb** [comment]
@jwhitcraft I am using ZSH and when I alias, completion just works fine. But I see that once I alias in bash, it doesn't do completion. I see many people use Bash so I take this must be a real pain point.

**Comment by jwhitcraft** [comment]
@ahmetb thanks for the info, i'll file an issue upstream.

**Comment by ahmetb** [comment]
Hi folks, sorry for auto-closing the issue with the commit. I found a solution. You can now `brew install kubectx --with-short-names` and it will install `kubectx` as `kctx` (and `kubens`, which I just added, as `kns`). With this option, we don’t have to rename the project. The bash/zsh completions should be working fine with shorthand names, too. Let me know if you run into any issues.

**Comment by rfay** [comment]
Thanks for this! I did uninstall and then `brew install kubectx --with-short-names` and now:

```
$ kctx
readlink: illegal option -- f
usage: readlink [-n] [file ...]
/usr/local/bin/kctx: line 28: ./../include/utils.bash: No such file or directory
```

**Comment by ahmetb** [comment]
@rfay ah yeah this is gnu vs bsd readlink difference. Subscribe to #8.

**Comment by ye** [comment]
@ahmetb sorry to inject into this old thread here, but did we get rid off the `--with-short-names` Homebrew option and the aliases? If so can you provide some explanation? I am actually getting used to use `kctx` and `kns` and changing that muscle memory is really hard...I mean I can alias those myself but I am curious to know what else is in `--with-short-names` .

https://github.com/ahmetb/kubectx/compare/v0.6.2...v0.6.3?expand=1
