### ISSUE TITLE
Feature: add `-version` or `--version` flag

### ISSUE THREAD

**Issue by qdm12** [ahmetb/kubectx#301]
It seems there is a version file to handle showing the version at https://github.com/ahmetb/kubectx/blob/master/cmd/kubectx/version.go

Which command or flag should we pass to `kubectx` to show the version?

If the flag already exists, then maybe adding it to the help message would be nice.

Thanks!

**Comment by ahmetb** [comment]
@qdm12 this is added to Go implementation only, make sure you use that.
The help message is already added. You probably are just not using the same version or I haven't made a release yet.

**Comment by trallnag** [comment]
@ahmetb, could it be that `--version` is only available in `>= 0.9.4`?

**Comment by ahmetb** [comment]
@trallnag version as well as it's only available in Go implementation of kubectx (that's still WIP and not all package managers pick it up).

**Comment by qdm12** [comment]
I can confirm `kubectx --version` only works since `v0.9.4`. Same for `kubens`.

Before you would get `error: unsupported option '--version'`.

This is for the Go version, I don't know about the shell version.

**Comment by sfc-gh-dswiecki** [comment]
@ahmetb what about adding this option to the shell version ? I see #295 adds this option only to go version. Do you have any plans for that ? Are you open to accept PR with version option for shell ?

**Comment by ahmetb** [comment]
Shell version is mostly in maintenance mode so you wouldn’t really need a version number there, plus it's a small single file script so I don't know why we'd need that there.
