### ISSUE TITLE
Add support for remote kubeconfigs (e.g. git repositories)

### ISSUE THREAD

**Issue by cndoit18** [ahmetb/kubectx#310]
I expect to be able to store `kubeconfig.yaml` in a git repository so that I can manage kubeconfigs via “kubectx + git"

**Comment by ahmetb** [comment]
I don't understand what you mean. Can you elaborate?

**Comment by cndoit18** [comment]
> I don't understand what you mean. Can you elaborate?

I have updated the description, do you think this can be understood

**Comment by ahmetb** [comment]
kubectx is not meant for CI/CD. It's a helper tool on top of kubectl. You can use kubectl directly if you want to modify your kubeconfig files. What you want sounds like another tool, not in the scope of this repo.
