### ISSUE TITLE
Brew install link 403

### ISSUE THREAD

**Issue by pnorth1** [ahmetb/kubectx#311]
When trying to install with brew from Mac OS Catalina, the install link is throwing 403 - Forbidden. Getting the same result in browser as well. 

https://homebrew.bintray.com/bottles/kubernetes-cli-1.20.4.catalina.bottle.tar.gz

**Comment by ahmetb** [comment]
Where did you get that link?

**Comment by pnorth1** [comment]
Oh, my bad, was in need of a brew update
