### ISSUE TITLE
kubectx xxx will sync to all secureCRT session

### ISSUE THREAD

**Issue by willzhang** [ahmetb/kubectx#315]
kubectx xxx will sync to all secureCRT session, Why not isolate between different sessions？

**Comment by ahmetb** [comment]
I don't understand what you're saying. Please be more descriptive and elaborate. I don't know what secureCRT even is. 

If you have a proposal you need to be more articulate than this. Please respect others' time.

**Comment by willzhang** [comment]
sorry ,what i mean
![kubectx.png](https://i.loli.net/2021/09/16/QNkivxCG1DSZLFr.png)

**Comment by ahmetb** [comment]
yeah that's currently expected and by design.
no way to do this easily unless we start a new shell subprocess with its own temp KUBECONFIG file.
#12 explains the same thing.
