### ISSUE TITLE
Automatically switch context per directory

### ISSUE THREAD

**Issue by ant31** [ahmetb/kubectx#318]
Hello,

I am looking for a way to auto switch context base on the current directory.
Something equivalent to pyenv with the .python-version and several other equivalent projects.

We are using kustomize with overlays. Each overlays is unique per context and  namespace:

```
Envs/staging/clusterX/appA
Envs/staging/clusterX/appB
Envs/staging/clusterZ/appA
Envs/staging/clusterZ/appB
Envs/prod/clusterX/appA
Envs/prod/clusterX/appB
Envs/prod/clusterZ/appA
Envs/prod/clusterZ/appB
```
Being able to drop a .kube-ctx   file that would switch automatically the context when entering the directory would be awesome.

Let me know what you think of this feature.

**Comment by ahmetb** [comment]
That would also require a per-shell hook (bash/zsh/fish/ps) that you'd need to register to your shell. I recommend using `direnv` (https://direnv.net/) as it's a general-purpose solution and doesn't need any implementation support from each tool you invoke.
