### ISSUE TITLE
Kubectx shuffle config content

### ISSUE THREAD

**Issue by koluchiy** [ahmetb/kubectx#319]
For example "kind: Config" moved from head to middle of config

**Comment by ahmetb** [comment]
@koluchiy please provide if this is Go implementation or Bash implementation + which version.

**Comment by koluchiy** [comment]
@ahmetb kubectx: stable 0.9.3, HEAD, installed from brew

**Comment by ahmetb** [comment]
@koluchiy that installs the bash implementation which calls into kubectl.
so it's actually kubectl who's reordering your fields. kubectl doesn't offer to keep your file cosmetics intact IIRC, so as far as kubectl is concerned, it's the same file.

if you download our Go implementation manually (soon to be stable), it will preserve the file structure.
