### ISSUE TITLE
Question: Is completion supported for the kubectl plugin?

### ISSUE THREAD

**Issue by jonaskello** [ahmetb/kubectx#321]
I installed both as kubectl plugin using krew and as regular terminal commands using [this method](https://github.com/ahmetb/kubectx/issues/282#issuecomment-912996229). The completion is working for the terminal commands but not for the kubectl plugin. Is there a way to get completion to work for the kubectl plugin or is it simply not supported? (Just want to know if it is possible before I spend more time trying to make it work).

**Comment by ahmetb** [comment]
Sadly no. :(
kubectl plugins don't have a shell completion planned yet. https://github.com/kubernetes/kubernetes/issues/74178

**Comment by blackliner** [comment]
/reopen
https://github.com/kubernetes/kubernetes/issues/74178 is closed, the feature is available

**Comment by ahmetb** [comment]
Krew does not have support for installing completion commands in PATH yet, so I'd say we tackle that first and worry about this case later (as most installations of kubectx aren't as a kubectl plugin).
