### ISSUE TITLE
Menu stoped working

### ISSUE THREAD

**Issue by JCzz** [ahmetb/kubectx#338]
Macos arm64
Installed:  brew install kubectx
kubectx 0.9.4

The menu is not working/showing as selectable

```
kubectx 
kind-kind
kind-kind-bob
kind-kind-internet
kind-kind-local

prompt>
```

But I can switch using kubectx <context> the menu from you can use the arrow do not work

**Comment by ahmetb** [comment]
Can you send some screenshots please I do not understand fully. Make sure you have fzf installed?
