### ISSUE TITLE
Packaging: Package for Debian bullseye or bullseye-backports

### ISSUE THREAD

**Issue by Northcode** [ahmetb/kubectx#342]
The Debian package is currently only available in: buster (oldstable), bookworm (testing) and sid (unstable).

Since bullseye is the new stable release, kubectx should be available there as well, if not, maybe in bullseye-backports, since its available in bookworm.

**Comment by ahmetb** [comment]
Any packaging help is appreciated. I don't use Ubuntu so I can't fix this. There's already a Snap pull request open and being worked on.

**Comment by ahmetb** [comment]
@martinreck packaging is not managed in this repository. I recommend reaching out to Debian package maintainer directly.

**Comment by martinreck** [comment]
I guess this is the repository for the Debian package: https://salsa.debian.org/debian/kubectx

**Comment by Northcode** [comment]
Considering packaging is not maintained here, I'm closing this issue.

I'm no longer using this on debian, so I'm not going to follow this up with the debian maintainer.
