### ISSUE TITLE
Completion with zsh + brew doesn't work

### ISSUE THREAD

**Issue by piclemx** [ahmetb/kubectx#347]
I'm trying to install `kubectx` on my new mac with the M1 chip.

I found something weird.

Seems I never get added the completions for `kubectx` or `kubeens`.

Something missing with `brew`?

I'm using `oh-my-zsh` + `brew`.

```
$ omz version
master (3427da4)
```

**Comment by piclemx** [comment]
I saw that the problem is more with homebrew + ohmyzsh..

I added the path of the `site-functions` to the my `.zshrc`

**Comment by bneigher** [comment]
@piclemx can you explain what you did here?

I've found some stuff in `/opt/homebrew/opt/kubectx/share/zsh/site-functions/`.  Where do I add this stuff?
Trying to get tab completion with kubectx.. getting nothing but dirs
