### ISSUE TITLE
Completions not working with oh-my-zsh on Linux

### ISSUE THREAD

**Issue by pk1914** [ahmetb/kubectx#35]
I am working on Linux with oh-my-zsh and I can't get completions to work.

I have updated my `fpath` line in `~/.oh-my-zsh/oh-my-zsh.sh` to be:
`fpath=($ZSH/functions $ZSH/completions /home/username/kubectx/completion $fpath)`

When I run `echo $fpath`, I get the expected output:
`... /home/username/kubectx/completion ...`

The directory above (`/home/username/kubectx/completion`) contains only one script, which is the [kubectx.zsh](https://github.com/ahmetb/kubectx/blob/master/completion/kubectx.zsh) script in the repo.

Have I done something wrong in the setup?

**Comment by ahmetb** [comment]
I have these lines in my .zshrc, which may help you:

https://github.com/ahmetb/dotfiles/blob/7b9f8c95d2ecb0df31c59525967f6305ce95360e/.zshrc#L37-L41

I'm not using Linux so I haven't tried the zsh completion there myself.

**Comment by pk1914** [comment]
Mine looks the same!

**Comment by ahmetb** [comment]
Hmm, when you type `_k` and hit <kbd>Tab</kbd>, do you see `_kubectx` and `_kubens` functions in the list?

**Comment by pk1914** [comment]
Nope.

**Comment by ahmetb** [comment]
But do you see it for commands like `_git` and `_ssh` ?

**Comment by pk1914** [comment]
I do! :)

**Comment by ahmetb** [comment]
I've reason to believe either `fpath` or `autoload`/`compinit` are not working correctly in this case.

Can you find where _ssh is (`find / -name '_ssh*'`) and try moving the completion scripts there, then restart your shell to see if you can kind _kubectx now.

**Comment by pk1914** [comment]
```
user -> /usr/share/zsh/5.0.2/functions -> sudo find / -name '_ssh*'
/usr/share/zsh/5.0.2/functions/_ssh
/usr/share/zsh/5.0.2/functions/_sshfs
```

I added the `kubectx.zsh` file found in completion/ in that folder. I still don't see `_kubectx` when I type `_k` and hit Tab.

**Comment by ahmetb** [comment]
I'm not sure when I can take a look at this problem. If anyone has time, definitely try to debug it.

In my setup (oh-my-zsh on macOS), Homebrew installation puts the completion scripts to the path I linked earlier, and it is working fine.

**Comment by edmeister** [comment]
The file names should start with an underscore to be loaded by zsh.

```
Completion functions for commands are stored in files with names beginning with an underscore _, and these files should be placed in a directory listed in the $fpath variable. You can add a directory to $fpath by adding a line like this to your ~/.zshrc file:

fpath=(~/newdir $fpath)
```

**Comment by pk1914** [comment]
Works now! Thanks @edmeister.

My final `fpath` is: `fpath=($ZSH/functions $ZSH/completions $fpath)`.

I put the `kubectx.zsh` file in `$ZSH/completions` folder and **renamed it** to `_kubectx`.

**Comment by ahmetb** [comment]
That's good to know. If we ever provide self-install instructions for zsh, I'll document it.

**Comment by utkuozdemir** [comment]
Had the same issue - in my case, probably after a MacOS upgrade or something, the used zsh switched from homebrew-installed zsh (`/usr/local/bin/zsh`) to the MacOS's own zsh, `/bin/zsh`. You can compare their versions via `/usr/local/bin/zsh --version` and `/bin/zsh --version`. To see the current version you are using, check `echo $ZSH_VERSION`, and also check `cat /etc/shells` to see a list of available shells.

If you are on MacOS zsh, you need to switch to the one comes from Homebrew, since that one has `/usr/local/share/zsh/site-functions` in FPATH - the location which `brew install kubectx` installs the completions.

To switch to Homebrew zsh, simply check your `/etc/shells`, if `/usr/local/bin/zsh` is missing, add it:
```
sudo bash -c 'echo /usr/local/bin/zsh >> /etc/shells'
```
then
```
chsh -s /usr/local/bin/zsh
```
Open a new shell and verify via `echo $ZSH_VERSION`

**Comment by ravindras85** [comment]
I am also having same issue, I have copied kubectx.zsh and kubens.zsh to $ZSH/completions, however its not showing in the list of functions when I use _k and hit Tab key. 
Also I have set an alias for kubectx, but whenever I execute the command kubectx, its gives me below message

$HOME/.oh-my-zsh/completions/kubectx.zsh: 3: local: not in a function

**Comment by chris-lee-parsable** [comment]
I installed kubectx with Homebrew, it's on the $fpath. I get this when -> 

 $ _kubens
_arguments:comparguments:325: can only be called from completion function
