### ISSUE TITLE
Correction to README.md instructions for "Completion scripts for bash" - fix permissions.

### ISSUE THREAD

**Issue by Kristianwhittick** [ahmetb/kubectx#354]
The existing instructions for "Completion scripts for bash" **do not** work due to permissions.

### Existing
1) Clone the repo.
Inconsistent: The manual installation example instructions include a clone already and the other shell examples assume the reader has followed the "manual install" example steps.

2) Create symbolic links in the completion folder.
**Problem**: A normal user will not have the necessary permissions.

3) Add the new clone of the repo to the path.
Inconsistent: Not necessary if the manual installation example was followed.

### Suggestion
Only three commands are needed.
a) The symbolic links require `sudo` as the directory location for the link is owned by root.
b) Change the path to the original clone location in the example installation.

```
COMPDIR=$(pkg-config --variable=completionsdir bash-completion)
sudo ln -sf /opt/kubectx/completion/kubens.bash $COMPDIR/kubens
sudo ln -sf /opt/kubectx/completion/kubectx.bash $COMPDIR/kubectx
```

**Comment by ahmetb** [comment]
Is this macOS or Linux? I suspect it worked for someone just fine, the challenge would be to find which one is more widely applicable.

**Comment by shtoltz** [comment]
Hi there.

According to the [bash-completion FAQ](https://github.com/scop/bash-completion#faq) `pkg-config --variable=completionsdir bash-completion` should be used when code completion is installed with a package (like installed with homebrew or apt, I assume)

With manual install (e.g. from git) the preferred way to install completions, according to the same FAQ, is to use:
* `$BASH_COMPLETION_USER_DIR` if set
* `$XDG_DATA_HOME/bash-completion` if `$XDG_DATA_HOME` is set
* `~/.local/share/bash-completion`

As a result, code should look something like this:
```
git clone https://github.com/ahmetb/kubectx.git ~/.kubectx
COMPDIR=${BASH_COMPLETION_USER_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/bash-completion}/completions
mkdir -p ${COMPDIR}
ln -sf ~/.kubectx/completion/kubens.bash ${COMPDIR}/kubens
ln -sf ~/.kubectx/completion/kubectx.bash ${COMPDIR}/kubectx
cat << EOF >> ~/.bashrc


#kubectx and kubens
export PATH=~/.kubectx:\$PATH
EOF
```

Line for `${COMPDIR}` I got from bash-completion source code (`grep -C3 '.local/share' /usr/share/bash-completion/bash_completion` on Ubuntu)

**Comment by shtoltz** [comment]
But yes, my code above applies to a local install kubectx/kubens for the current user only.
If kubectx/kubens are already installed globally, it makes sense to install completions globally also, as @Kristianwhittick suggested.
