### ISSUE TITLE
kubectx kubens in centos7 run error

### ISSUE THREAD

**Issue by haozi4263** [ahmetb/kubectx#36]
error log:
/usr/local/bin/kubectx: line 30: /usr/local/bin/../include/utils.bash: No such file or directory

**Comment by ahmetb** [comment]
@haozi4263 how did you install.

We recently deleted `utils.bash`. So if you're getting the latest kubectx/kubens scripts from this repo, you shouldn't be seeing this error.

**Comment by haozi4263** [comment]
wget https://github.com/ahmetb/kubectx/archive/v0.4.0.tar.gz
cp kubens kubectx /usr/local/bin

**Comment by ahmetb** [comment]
ah! that would require you to `cp utils.bash /usr/local/include/`

can you use `master` instead (https://github.com/ahmetb/kubectx/archive/master.tar.gz)?

**Comment by haozi4263** [comment]
ok 
use https://github.com/ahmetb/kubectx/archive/master.tar.gz is ok
thanks!
