### ISSUE TITLE
Support winget

### ISSUE THREAD

**Issue by chingucoding** [ahmetb/kubectx#365]
Right now, kubectx can only be installed on windows using Choco, however Windows also has its own package manager now called winget. It would be great if that was also supported.

**Comment by ahmetb** [comment]
This repository doesn't handle packaging issues. Feel free to package it and publish it yourself.

**Comment by Okeanos** [comment]
I created manifests for [kubectx](https://github.com/microsoft/winget-pkgs/pull/95635) and [kubens](https://github.com/microsoft/winget-pkgs/pull/95921). Actually without even knowing this issue exists 😅 .

Once the `kubens` PR is through you can update the readme and add the install instructions for both binaries.

**Comment by chingucoding** [comment]
Awesome, thank you so much @Okeanos and @ahmetb !
