### ISSUE TITLE
kubectx is not session aware

### ISSUE THREAD

**Issue by omerlin** [ahmetb/kubectx#366]
This is more a question than an issue.
Is it possible to use kubectx to set a cluster for a complete Unix session ?
Meaning i can do one times `kubectl dev` and use kubectl commands without risk that someone else in another session switch the context to another session by a `kubectl dev2` command ?

I have the impression that i need to set a KUBECONFIG variable in each session.
Do i'm right ?
Thanks for you help and suggestion

**Comment by ahmetb** [comment]
There's an open issue about this.

**Comment by omerlin** [comment]
Sorry - i checked all the opened issues and didn't find it ? please could you give me the link ?
