### ISSUE TITLE
Feature Idea: Namespace creation

### ISSUE THREAD

**Issue by Bloeckchengrafik** [ahmetb/kubectx#367]
Hello,

I think the automatic creation of a namespace if it doesn't exists would benefit the workflow with the kubens tool.

Perhaps, it could be implemented like this
```
$ kubens test
error: no namespace exists with name "test".
Would you like to create a namespace named "test" in the cluster "remote"? [y,N]
```

If wanted, I could also implement this.

sincerely, Christian

**Comment by ahmetb** [comment]
Sounds like feature creep to me. :)

**Comment by Bloeckchengrafik** [comment]
Okay!
