### ISSUE TITLE
Add kubectl plugin installation to Homebrew formula

### ISSUE THREAD

**Issue by justenstall** [ahmetb/kubectx#397]
Is there a reason the kubectx Homebrew formula only installs the binaries as `kubectx` and `kubens`? The following lines could be added to the formula to also install the binaries as kubectl plugins, and wouldn't create much overhead since Homebrew uses symlinks:

```rb
  def install
    bin.install "kubectx", "kubens" # already in formula
    
    bin.install "kubectx" => "kubectl-ctx"
    bin.install "kubens" => "kubectl-ns"
    ...
  end
```

If there isn't a reason against it, I can make a PR to the [homebrew-core repo](https://github.com/Homebrew/homebrew-core/blob/master/Formula/kubectx.rb) with the change.

**Comment by ahmetb** [comment]
Honestly not a bad idea but it might confuse people a bit regarding where these plugins are from if they also have Krew installed on their system but these plugins aren't showing up on `kubectl krew list`. (For example, I use krew for other plugins but not for kubectx/kubens.)

**Comment by ahmetb** [comment]
Yeah makes sense. Go for it, I see no harm except when this shadows krew installation for the same plugin and vice versa, but it's not a big deal.

**Comment by justenstall** [comment]
This was implemented with https://github.com/Homebrew/homebrew-core/pull/140831
