### ISSUE TITLE
kubectx -d: add shell completion (zsh)

### ISSUE THREAD

**Issue by ahmetb** [ahmetb/kubectx#40]
I just realized we didn't code the bash/zsh/fish completions in a way that it can complete context names in subcommands like `-d`.

"$ kubectx -d <kbd>Tab</kbd><kbd>Tab</kbd>" should suggest some context to delete. 

Additionally, in case of `-d`, supporting multiple arguments for (#39) would require completion scripts should to auto-complete context names in multiple positions ($2, $3, ... $N) as well.

**Comment by luisejrobles** [comment]
I'll work on it! 🎃

**Comment by luisejrobles** [comment]
It's working in my environment 🤔

**Comment by ahmetb** [comment]
Ah, I forgot to tell I'm trying in zsh.

**Comment by luisejrobles** [comment]
alright, let me check

**Comment by arbourd** [comment]
works with fish! somehow :D
