### ISSUE TITLE
show all of NAME, CLUSTER and AUTHINFO in cluster selection list

### ISSUE THREAD

**Issue by jogomu** [ahmetb/kubectx#401]
```
CURRENT   NAME                                                  CLUSTER                                               AUTHINFO                                              NAMESPACE
```

NAME, CLUSTER and AUTHINFO are all potentially helpful in identifying a cluster.  Can we show all of these in the kubectx list please?

**Comment by ahmetb** [comment]
It’s not this tool’s job to copy exactly what `kubectl config get-contexts` does. 

Furthermore, the output of kubectx is directly fed to tools like fzf (and unfortunately people script around it) so it’s neither feasible nor makes sense.

**Comment by jogomu** [comment]
ok, I just hacked the script to show get-contexts first above the kubectx-controlled portion of the terminal
