### ISSUE TITLE
doc: how to add new context?

### ISSUE THREAD

**Issue by glensc** [ahmetb/kubectx#42]
so i have minikube in output, how do i add new "context"?

please add such section to readme.

**Comment by ahmetb** [comment]
I don’t understand this question fully. 

Your contexts come from kubectl. See “kubectl config” commands.

**Comment by glensc** [comment]
yes, if that is the information, include it into readme. improves learning curve for newcomers.

**Comment by HalisCz** [comment]
I have a bunch of kubeconfig files (one for each cluster) spread among my folders.

I found out this promising tool, and I would like to import those kubeconfig files to kubectx, but I do not know how, and I am not able to find any howto on this. Only thing that I found is this issue.

Would you mind to explain this to me?

**Comment by ahmetb** [comment]
@HalisCz https://medium.com/@ahmetb/mastering-kubeconfig-4e447aa32c75

**Comment by HalisCz** [comment]
@ahmetb Thank you, that is exactly what I was asking for.

**Comment by JeremyMordkoff** [comment]
I know this item is closed, but I don't think it's been answered. kubectl does not have a command line option to copy a context. Example...I have a context that let's me focus on namespace foo in cluster x. I deploy something new to namespace bar in cluster x, so now I want to create a new context so I can focus on the new deployment. I have to open the kubeconfig file with an editor and add the new context. I'd really like to be able to do 

kubectx copy foo bar   ## new command option to copy a context 
kubectx bar 
kubectl config set-context --current --namespace=bar

or even better 

kubectx copy foo bar --current --namespace=bar   ## make it current and reset the namespace :
