### ISSUE TITLE
Feature-Request: Enable kubens to be used without cluster scope permissions

### ISSUE THREAD

**Issue by jnt0r** [ahmetb/kubectx#424]
Currently I'm not able to use kubens as I do not have cluster scope permissions. Therefore I recieve the following error when using kubens:

`Error from server (Forbidden): namespaces is forbidden: User "XXXXXXX" cannot list resource "namespaces" in API group "" at the cluster scope
error getting namespace list
error: could not list namespaces (is the cluster accessible?)`

It would be nice to be able to use kubens without cluster scope permissions.

**Comment by ahmetb** [comment]
Just merged #416 to fix this but have not made a release.
