### ISSUE TITLE
kubectl ns not rendering correctly in some terminals

### ISSUE THREAD

**Issue by tguskiptc** [ahmetb/kubectx#433]
I am currently running kubectx and kubens in a vscode python devcontainer . The version from the Dockerfile:
			"BASE_IMAGE_REPO":"mcr.microsoft.com",
			"BASE_IMAGE_LOCATION":"devcontainers/python",
			"BASE_IMAGE_TAG":"1-3.12-bookworm",

I install kubectx and kubens in the Dockerfile as follows:

```
ARG BASE_IMAGE_REPO
ARG BASE_IMAGE_LOCATION
ARG BASE_IMAGE_TAG
FROM ${BASE_IMAGE_REPO}/${BASE_IMAGE_LOCATION}:${BASE_IMAGE_TAG}

ENV OS=linux \
  ARCH=amd64 \
  KUBELOGIN_VERSION=v0.0.30 \
  PYDEVD_DISABLE_FILE_VALIDATION=1

ARG UBUNTU_UID
ARG UBUNTU_USERNAME
RUN useradd -u ${UBUNTU_UID} -ms /bin/bash ${UBUNTU_USERNAME}

RUN echo Installing kubectl
RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.29.7/bin/linux/amd64/kubectl && \
  mv kubectl /usr/bin/ && \
  chmod +x /usr/bin/kubectl

USER ${UBUNTU_USERNAME}

RUN set -x; cd "$(mktemp -d)" && \
  OS="$(uname | tr '[:upper:]' '[:lower:]')" && \
  ARCH="$(uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/')" && \
  KREW="krew-${OS}_${ARCH}" && \
  curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/latest/download/${KREW}.tar.gz" && \
  tar zxvf "${KREW}.tar.gz" && \
  ./"${KREW}" install krew
RUN echo "export PATH=\"${KREW_ROOT:-$HOME/.krew}/bin:$PATH\"" >> ~/.bashrc

RUN export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH" && kubectl krew install ctx
RUN export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH" && kubectl krew install ns
```

kubectl ctx and kubectl ns both work from the terminal - but they don't render correctly:
![image](https://github.com/user-attachments/assets/520b9f99-3d58-4f5a-8d4f-6d59d79988d0)

Wondering what's wrong with my install...
Thanks for your great tools!

**Comment by ahmetb** [comment]
There's a reason why installation instructions at https://krew.sigs.k8s.io/docs/user-guide/setup/install/ have parentheses around "set -x". :)

**Comment by tguskiptc** [comment]
Determined that DEBUG is set to true which is causing script `~/.krew/bin/kubectl-ns` to do the following at the start: `[[ -n $DEBUG ]] && set -x` which causes the debug output making everything look off. Commenting out this line fixes the issue and makes everything look correct.
