### ISSUE TITLE
Fish completions install incorrectly through homebrew

### ISSUE THREAD

**Issue by tylercunnion** [ahmetb/kubectx#50]
Performing a `brew install kubectx` results in the completion files being symlinked to `_kubectx` and `_kubens` within the fish vendor completions directory. These don't appear to be getting parsed (I'm using fish 2.7.1, also installed via homebrew).

Moving these files to `kubectx.fish` and `kubens.fish` solves this and makes completions available.

(I realize the change will have to be made in the homebrew repository, not this one, but this seemed the right place to open up the issue)

**Comment by ahmetb** [comment]
This should now be fixed. Try “brew update” and reinstall kubectx.
