### ISSUE TITLE
why kubernetes-cli installed via brew?

### ISSUE THREAD

**Issue by xmlking** [ahmetb/kubectx#56]
I already have `kubectl` in my path via "Docker for Mac"
why `brew install kubectx` again installing `kubernetes-cli ` ?

**Comment by ahmetb** [comment]
Because other people might not have it in their PATH and docker is not a package manager? 😊 There’s no way for brew to ignore something just because it appears in your PATH.

**Comment by xmlking** [comment]
found solution 
`brew install   --ignore-dependencies --with-short-names kubectx`
Thanks
