### ISSUE TITLE
Unable to run kubectx with short name (kctx) on Mac

### ISSUE THREAD

**Issue by natraj09** [ahmetb/kubectx#58]
Hi,

I tried to install kubectx on Mac using ` brew install kubectx --with-short-names` .

When I try to run `kctx` , I get an error `error: converting  to : type names don't match (Unknown, RawExtension), and no conversion 'func (runtime.Unknown, runtime.RawExtension) error' registered.`

Any idea what could be wrong?

**Comment by ahmetb** [comment]
Sounds like kctx is actually something else. Can you run “which kctx” to verify?

**Comment by ahmetb** [comment]
looks like this is coming from kubernetes. found a similar issue here. https://github.com/kubernetes/minikube/issues/1618

I'm suspecting that this is an issue on your computer. Are you able to run `kubectl get pods` or `kubectl version` fine?

please run `DEBUG=1 kctx` and print the output here.

**Comment by natraj09** [comment]
I am able to run `kubectl version` and `kubectl get pods`
```+ set -eou pipefail
+ IFS='
	'
+ KUBECTX=/Users/nsrinivasan/.kube/kubectx
+ main
+ [[ 0 -eq 0 ]]
+ list_contexts
+ set -u pipefail
+ local cur
++ current_context
++ kubectl config view '-o=jsonpath={.current-context}'
error: converting  to : type names don't match (Unknown, RawExtension), and no conversion 'func (runtime.Unknown, runtime.RawExtension) error' registered.
+ cur=```

**Comment by ahmetb** [comment]
Clearly the issue is in your `kubectl config view '-o=jsonpath={.current-context}'` command. If you installed it with `kubectx` , it would still fail.

1. Run  `kubectl config view '-o=jsonpath={.current-context}'` directly and tell me if it fails with that error.
2. Please paste the output of `kubectl config view`.

**Comment by natraj09** [comment]
I am able to run `kubectl config view '-o=jsonpath={.current-context}'  

I realized I have an alias for kubectl , we have a custom binary used in our company which is packaged with kubectl.  In my `~/.bashrc`  my alias is alias kubectl = `tess kubectl`. As this a unique use case . I'll try to figure out how to make it work for our use case.

We can close this issue.

**Comment by natraj09** [comment]
Figured out a work around by creating a fake executable under /usr/local/bin
```#!/bin/sh
~/./tess kubectl  "$@"```
