### ISSUE TITLE
add Japanese translation

### ISSUE THREAD

**Issue by koh7** [ahmetb/kubectx#59]
Hi.

I’m a fun of your project.
I’ve thought it will be nice if there is a Japanese version of README, because I sometimes have to make a small lesson about how to use/install this project for new employees who can not read English.

So I decided to add README in Japanese and create a pull request, although I’m not sure whether the location of README_ja.md is appropriate or not.
Please give me your opinion. 

Finally, when you want to update README, just create an issue or contact me. I’ll be happy to modify README_ja.md based on the changes of the original README. 

Thanks!

**Comment by ahmetb** [comment]
I appreciate the contribution but the same goes for many other languages. I don’t think it’s a widespread practice in projects of this size to maintain multilingual readmes. I cannot maintain the Japanese (or any other language) README up-to-date myself, so I prefer not to have this.

**Comment by koh7** [comment]
Okay, I understand. 
Thanks for your concern.
