### ISSUE TITLE
Add "default" context and/or namespace

### ISSUE THREAD

**Issue by sidewinder12s** [ahmetb/kubectx#70]
Would there be any way to add a "default" namespace and cluster context that kubectx would switch to either after a timeout or in each new bash window?

Primarily to make it harder to accidentally apply something to a production cluster.

**Comment by ahmetb** [comment]
This is tough to design. Most users don't expect something like a timeout and the timeout-based approach makes things harder.

I have this proposal for a while https://github.com/ahmetb/kubectx/issues/12 it might work for you. Please read and let me know if that existed, would that solve your problem?

**Comment by sidewinder12s** [comment]
I think it'd help, if I'm understanding it correctly. I've got 6 clusters now with another 6 that I could add and just wanted to make it harder to accidentally hit the production clusters with something unexpected.  

I suppose I could also just add something to my bashrc to just reset on every new window.

**Comment by ahmetb** [comment]
I'll close this as I see no way of implementing this in a good way.

I recommend you add this to your crontab or bashrc. Thanks for bringing it up.
