### ISSUE TITLE
Add fzf support for interactive search

### ISSUE THREAD

**Issue by ahmetb** [ahmetb/kubectx#71]
We can optionally support fzf if it is in the PATH to provide interactive context selecting with partial/fuzzy input! 

it would work like:

```
if len(args) == 1 && output is tty && fzf in path:
    # interactive mode
    choice="$(FZF_DEFAULT_COMMAND=kubectx NO_COLOR=1 fzf)"
	set_context $choice
else:
    # non-interactive mode (list contexts and exit)
    list_contexts
end
```

Anyone like this?

**Comment by ahmetb** [comment]
if anyone's interested, check out branch https://github.com/ahmetb/kubectx/tree/fzf-support

**Comment by gowtham-sai** [comment]
How do I see current context with this? Whenever I type kubectx it opens up fzf :(

**Comment by ahmetb** [comment]
1. Fzf shows current context with yellow color.
2. There’s a way to disable fzf in the readme.
3. See #125.
4. Please open new issues to ask questions. Closed issues aren’t good for this.

**Comment by gowtham-sai** [comment]
Extreme  apologies..! Directly landed on the issue page and didn't check README. I have another issue with it, will create new issue. 

Thanks 👍
