### ISSUE TITLE
Since 0.6.0 kctx doesn't work anymore

### ISSUE THREAD

**Issue by adebasi** [ahmetb/kubectx#78]
**Setup:**
I am using MacOS and installed `kubectx` this way:
```
brew install kubectx --with-short-names
```
I just upgraded to 0.6.0.

**Problem:**
Running `kctx` command shows fzf-view and `[$FZF_DEFAULT_COMMAND failed]`

**Cause:**
I found the line of code which causes trouble: https://github.com/ahmetb/kubectx/blob/master/kubectx#L94
```
choice="$(FZF_DEFAULT_COMMAND='kubectx' fzf --ansi || true)"
```
`kubectx` does not exist in my environment, because I installed `kubectx` with `--with-short-names`. I only have `kctx`

**Comment by ahmetb** [comment]
You can now download 0.6.1 via brew.
