### ISSUE TITLE
kubectx and kubens no longer work on macOS due to missing readlink -f option

### ISSUE THREAD

**Issue by koenrh** [ahmetb/kubectx#8]
Hi Ahmet, first of all, excellent tool!

This morning, I noticed that the current versions of both `kubectx` and `kubens` no longer (since https://github.com/ahmetb/kubectx/pull/6) work on macOS (and possibly other BSD-based systems), because `readlink` on these systems don't know about the `-f` option (to follow symlinks, and canonicalise the name).

```bash
$ kubens

readlink: illegal option -- f
usage: readlink [-n] [file ...]
/usr/local/bin/kubens: line 28: ./../include/utils.bash: No such file or directory
```

We could either require the GNU version of `readlink` (which supports `-f`/`--canonicalize`), and add a `case` to use `greadlink` on macOS, or add our own function that behaves like GNU's `readlink`, i.e. iterate through symlinks, and return the canonical name.

**Comment by lypht** [comment]
@koenrh I just ran into this myself.  The following resolved my local instance:

`brew install coreutils`

I then added gnubin to my path by appending 

`export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"` to $HOME/.bash_profile, and restarting my terminal.

I agree that the additional case requirement would be a helpful addition, but until that point, if others are using this fantastic tool, these three steps might help some folks.

**Comment by ahmetb** [comment]
My bad. I keep forgetting gnu coreutils is installed on my Mac. I wonder if we can do without -f and without checking for greadlink.

**Comment by rfay** [comment]
In the brew recipe you might be able to make coreutils a dependency and then use greadlink? Seems like a hard sell.

**Comment by ahmetb** [comment]
Since `readlink -f` fails only on BSD coreutils which is on mac, I think we can safely assume Python is installed. So I am changing the way to determine SCRIPT_DIR to this, which falls back to Python:

```sh
SCRIPT_DIR="$(dirname $( readlink -f "${0}" 2>/dev/null || \
  python -c "import os,sys; print(os.path.realpath(sys.argv[1]))" "${0}" ))"
```

Every method I found without introducing GNU coreutils dependency is just a hack, including this one. I’ll submit a PR soon and make a release. Sorry for the disruption.

**Comment by koenrh** [comment]
@ahmetb What do think of this? https://github.com/kubernetes/kubernetes/blob/b353700bfc1ee95b8f9f827c9cc818cf2ab3f943/hack/lib/init.sh#L111-L128

**Comment by ahmetb** [comment]
@koenrh it's nice but we would be copying it to 2 files, both kubens/kubectx scripts. So I prefer a one-liner more.

**Comment by ahmetb** [comment]
Fixed, try with `brew update && brew upgrade`.

**Comment by rfay** [comment]
Works for me, thanks!
