### ISSUE TITLE
Add merge/import command

### ISSUE THREAD

**Issue by fkrauthan** [ahmetb/kubectx#85]
Would it be possible to add a merge/import command where I could specify a kubeconfig file (e.g. generated by different systems) to import that kubeconfig file and append/merge it with the default `~/.kube/config` file?

**Comment by ahmetb** [comment]
:) 

What you're looking for is:

    KUBECONFIG=file1:file2 kubectl config view --minify > ~/.kube/config

**Comment by fkrauthan** [comment]
Oh cool didn't know that exist. I still think a shortcut method like `kubectx import ./file1` would be more preferable (given that everything this util does exist anyways except shorter and more easy accessible)

**Comment by ahmetb** [comment]
I just don't think it's a super common operation that people do out there. But if this comes up from other people, I'll be open to doing it. I'm trying to keep feature creep out and keep the tool focused.

**Comment by fkrauthan** [comment]
Hmm I just tested your solution and successful destroyed my kubeconfig file (thats on me). But unfortunately specifying multiple kubeconfig files in `KUBECONFIG` and using config view retracts certificate information which renders the result not usable.

**Comment by ahmetb** [comment]
> specifying multiple kubeconfig files in KUBECONFIG and using config view redacts certificate information

This is my bad. :) I should've told you to use `kubectl config view --merge --flatten`. This preserves both cluster `certficate-authority-data` and user `client-{certificate,key}-data` fields. (see kubemci repo for example usages of this).

**Comment by naphta** [comment]
It would be a pretty useful thing to have as theres one specific use case which the above example doesn't cater to; if you're importing a configuration where one of the fields has the same name but different values; e.g. same username different token / ca.

I think it'd make more sense for it to be a different script though; kubecfg for example?

**Comment by ahmetb** [comment]
We have some kubectl plugins in Krew (http://krew.dev) already doing this, and there are even desktop tools like https://github.com/turkenh/KubeContext/blob/master/README.md#installation that do similar things.
