### ISSUE TITLE
How do you configure your clusters?

### ISSUE THREAD

**Issue by rhugga** [ahmetb/kubectx#99]
This tool seems great and all but where are the docs on how to configure you clusters? I assume a directory structure of some sort with kubeconfig files right? I have all mine under ~/.kube, this tool doesn't seem to find them automagically.

**Comment by ahmetb** [comment]
This tool operates on existing kubeconfig files. If your cloud provider or kubernetes set up script is not giving you a kubeconfig file or configuring ~/.kube/config, contact them.
